-- SAPLE SUPABASE POSTGRESQL SCHEMA

BEGIN;

-- ================================================================
-- 1. ACCOUNTS AND IDENTITY
-- ================================================================

-- USERS stores login identity, account state and authorization.
-- ACCOUNT_ROLE is independent from USER_TYPE.
CREATE TABLE users (
    user_id        BIGINT GENERATED BY DEFAULT AS IDENTITY,
    full_name      VARCHAR(120) NOT NULL,
    email          VARCHAR(254) NOT NULL,
    password_hash  VARCHAR(255) NOT NULL,
    user_type      VARCHAR(10) DEFAULT 'NORMAL' NOT NULL,
    account_role   VARCHAR(25) DEFAULT 'USER' NOT NULL,
    account_status VARCHAR(15) DEFAULT 'ACTIVE' NOT NULL,
    token_version  INTEGER DEFAULT 0 NOT NULL,
    avatar_path    VARCHAR(500),
    headline       VARCHAR(160),
    bio            VARCHAR(2000),
    created_at     TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL, --more precision than DATE
    updated_at     TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (user_id),
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT ck_users_full_name CHECK (TRIM(full_name) <> ''),
    CONSTRAINT ck_users_email CHECK (TRIM(email) <> ''),
    CONSTRAINT ck_users_password_hash CHECK (LENGTH(password_hash) >= 20),
    CONSTRAINT ck_users_type CHECK (user_type IN ('NORMAL', 'EMPLOYEE')),
    CONSTRAINT ck_users_role CHECK (account_role IN ('USER', 'ADMIN', 'COMPANY_REPRESENTATIVE')),
    CONSTRAINT ck_users_status CHECK (account_status IN ('ACTIVE', 'SUSPENDED', 'DEACTIVATED')),
    CONSTRAINT ck_users_token_version CHECK (token_version >= 0)
);

CREATE TABLE user_education (
    education_id       BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id            BIGINT NOT NULL,
    institution        VARCHAR(180) NOT NULL,
    degree             VARCHAR(160) NOT NULL,
    field_of_study     VARCHAR(160) NOT NULL,
    start_date         DATE NOT NULL,
    end_date           DATE,
    currently_studying BOOLEAN DEFAULT FALSE NOT NULL,
    description        VARCHAR(2000),
    CONSTRAINT pk_user_education PRIMARY KEY (education_id),
    CONSTRAINT fk_user_education_user FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE,
    CONSTRAINT ck_user_education_institution CHECK (TRIM(institution) <> ''),
    CONSTRAINT ck_user_education_degree CHECK (TRIM(degree) <> ''),
    CONSTRAINT ck_user_education_field CHECK (TRIM(field_of_study) <> ''),
    CONSTRAINT ck_user_education_dates CHECK (
        (currently_studying AND end_date IS NULL)
        OR (NOT currently_studying AND end_date IS NOT NULL AND end_date >= start_date)
    )
);
CREATE INDEX idx_user_education_user ON user_education (user_id, start_date DESC);

CREATE TABLE user_experience (
    experience_id      BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id            BIGINT NOT NULL,
    organization       VARCHAR(180) NOT NULL,
    job_title          VARCHAR(160) NOT NULL,
    employment_type    VARCHAR(60),
    location           VARCHAR(160),
    start_date         DATE NOT NULL,
    end_date           DATE,
    currently_working  BOOLEAN DEFAULT FALSE NOT NULL,
    description        VARCHAR(2000),
    CONSTRAINT pk_user_experience PRIMARY KEY (experience_id),
    CONSTRAINT fk_user_experience_user FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE,
    CONSTRAINT ck_user_experience_organization CHECK (TRIM(organization) <> ''),
    CONSTRAINT ck_user_experience_title CHECK (TRIM(job_title) <> ''),
    CONSTRAINT ck_user_experience_dates CHECK (
        (currently_working AND end_date IS NULL)
        OR (NOT currently_working AND end_date IS NOT NULL AND end_date >= start_date)
    )
);
CREATE INDEX idx_user_experience_user ON user_experience (user_id, start_date DESC);

CREATE TABLE skills (
    skill_id   BIGINT GENERATED BY DEFAULT AS IDENTITY,
    skill_name VARCHAR(80) NOT NULL,
    CONSTRAINT pk_skills PRIMARY KEY (skill_id),
    CONSTRAINT ck_skills_name CHECK (TRIM(skill_name) <> '')
);
CREATE UNIQUE INDEX uk_skills_name_ci ON skills (LOWER(skill_name));

CREATE TABLE user_skills (
    user_id  BIGINT NOT NULL,
    skill_id BIGINT NOT NULL,
    CONSTRAINT pk_user_skills PRIMARY KEY (user_id, skill_id),
    CONSTRAINT fk_user_skills_user FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE,
    CONSTRAINT fk_user_skills_skill FOREIGN KEY (skill_id) REFERENCES skills (skill_id) ON DELETE RESTRICT
);

-- EMPLOYEES is the optional one-to-one employment profile for a user.
CREATE TABLE employees (
    employee_id       BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id           BIGINT NOT NULL,
    employment_status VARCHAR(10) NOT NULL,
    created_at        TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_employees PRIMARY KEY (employee_id),
    CONSTRAINT uk_employees_user UNIQUE (user_id),
    CONSTRAINT fk_employees_user FOREIGN KEY (user_id)
        REFERENCES users (user_id) ON DELETE CASCADE,
    CONSTRAINT ck_employees_status CHECK (employment_status IN ('CURRENT', 'FORMER'))
);

-- PASSWORD_RESET_TOKENS stores only single-use, expiring token hashes.
CREATE TABLE password_reset_tokens (
    reset_token_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id        BIGINT NOT NULL,
    token_hash     VARCHAR(64) NOT NULL,
    expires_at     TIMESTAMPTZ NOT NULL,
    used_at        TIMESTAMPTZ,
    revoked_at     TIMESTAMPTZ,
    created_at     TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_password_reset_tokens PRIMARY KEY (reset_token_id),
    CONSTRAINT uk_password_reset_token_hash UNIQUE (token_hash),
    CONSTRAINT fk_password_reset_user FOREIGN KEY (user_id)
        REFERENCES users (user_id) ON DELETE CASCADE,
    CONSTRAINT ck_password_reset_token_hash CHECK (LENGTH(token_hash) = 64),
    CONSTRAINT ck_password_reset_expiry CHECK (expires_at > created_at),
    CONSTRAINT ck_password_reset_state CHECK (used_at IS NULL OR revoked_at IS NULL)
);

-- ================================================================
-- 2. COMPANY REFERENCE DATA
-- ================================================================

-- COMPANIES stores the public reference profile for each company.
CREATE TABLE companies (
    company_id        BIGINT GENERATED BY DEFAULT AS IDENTITY,
    company_name      VARCHAR(150) NOT NULL,
    industry          VARCHAR(100) NOT NULL,
    headquarters_city VARCHAR(100) NOT NULL,
    country           VARCHAR(100) NOT NULL,
    website           VARCHAR(255),
    company_size      VARCHAR(30),
    description       TEXT, --character large object
    logo_path         VARCHAR(500),
    created_at        TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at        TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_companies PRIMARY KEY (company_id),
    CONSTRAINT uk_companies_name UNIQUE (company_name),
    CONSTRAINT ck_companies_name CHECK (TRIM(company_name) <> ''),
    CONSTRAINT ck_companies_industry CHECK (TRIM(industry) <> ''),
    CONSTRAINT ck_companies_city CHECK (TRIM(headquarters_city) <> ''),
    CONSTRAINT ck_companies_country CHECK (TRIM(country) <> '')
);

-- JOB_ROLES is the reusable catalog of job designations.
CREATE TABLE job_roles (
    role_id       BIGINT GENERATED BY DEFAULT AS IDENTITY,
    role_name     VARCHAR(120) NOT NULL,
    role_category VARCHAR(100),
    description   VARCHAR(500),
    CONSTRAINT pk_job_roles PRIMARY KEY (role_id),
    CONSTRAINT uk_job_roles_name UNIQUE (role_name),
    CONSTRAINT ck_job_roles_name CHECK (TRIM(role_name) <> '')
);

-- BENEFITS is the reusable catalog of employee benefits.
CREATE TABLE benefits (
    benefit_id       BIGINT GENERATED BY DEFAULT AS IDENTITY,
    benefit_name     VARCHAR(120) NOT NULL,
    benefit_category VARCHAR(100),
    description      VARCHAR(500),
    CONSTRAINT pk_benefits PRIMARY KEY (benefit_id),
    CONSTRAINT uk_benefits_name UNIQUE (benefit_name),
    CONSTRAINT ck_benefits_name CHECK (TRIM(benefit_name) <> '')
);

-- COMPANY_BENEFITS resolves the company-benefit many-to-many relationship.
CREATE TABLE company_benefits (
    company_id  BIGINT NOT NULL,
    benefit_id  BIGINT NOT NULL,
    details     VARCHAR(500),
    eligibility VARCHAR(250),
    last_updated TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_company_benefits PRIMARY KEY (company_id, benefit_id),
    CONSTRAINT fk_company_benefits_company FOREIGN KEY (company_id)
        REFERENCES companies (company_id) ON DELETE CASCADE,
    CONSTRAINT fk_company_benefits_benefit FOREIGN KEY (benefit_id)
        REFERENCES benefits (benefit_id) ON DELETE CASCADE
);

-- ================================================================
-- 3. EMPLOYMENT VERIFICATION
-- ================================================================

-- EMPLOYMENT_VERIFICATIONS scopes employee trust to a company and job role.
-- ROLE_ID remains nullable only for migration-07 legacy compatibility.
CREATE TABLE employment_verifications (
    verification_id     BIGINT GENERATED BY DEFAULT AS IDENTITY,
    employee_id         BIGINT NOT NULL,
    company_id          BIGINT NOT NULL,
    role_id             BIGINT,
    verification_method VARCHAR(30) NOT NULL,
    company_email       VARCHAR(254),
    proof_type          VARCHAR(30),
    proof_reference     VARCHAR(255),
    verification_status VARCHAR(10) DEFAULT 'PENDING' NOT NULL,
    requested_at        TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    reviewed_at         TIMESTAMPTZ,
    expires_at          TIMESTAMPTZ,
    rejection_reason    VARCHAR(500),
    reviewed_by         BIGINT,
    CONSTRAINT pk_employment_verifications PRIMARY KEY (verification_id),
    CONSTRAINT fk_emp_verify_employee FOREIGN KEY (employee_id)
        REFERENCES employees (employee_id) ON DELETE CASCADE,
    CONSTRAINT fk_emp_verify_company FOREIGN KEY (company_id)
        REFERENCES companies (company_id) ON DELETE CASCADE,
    CONSTRAINT fk_emp_verify_role FOREIGN KEY (role_id)
        REFERENCES job_roles (role_id),
    CONSTRAINT fk_emp_verify_reviewer FOREIGN KEY (reviewed_by)
        REFERENCES users (user_id),
    CONSTRAINT ck_emp_verify_method CHECK (verification_method IN ('COMPANY_EMAIL_OTP', 'DOCUMENT')),
    CONSTRAINT ck_emp_verify_status CHECK (verification_status IN ('VERIFIED', 'PENDING', 'REJECTED', 'EXPIRED')),
    CONSTRAINT ck_emp_verify_proof CHECK (
        (verification_method = 'COMPANY_EMAIL_OTP' AND company_email IS NOT NULL AND proof_reference IS NULL)
        OR
        (verification_method = 'DOCUMENT' AND proof_type IS NOT NULL AND proof_reference IS NOT NULL AND company_email IS NULL)
    ),
    CONSTRAINT ck_emp_verify_review CHECK (
        (verification_status = 'PENDING' AND reviewed_at IS NULL AND reviewed_by IS NULL)
        OR
        (verification_status <> 'PENDING' AND reviewed_at IS NOT NULL AND reviewed_by IS NOT NULL)
    ),
    CONSTRAINT ck_emp_verify_rejection CHECK (
        verification_status = 'REJECTED' OR rejection_reason IS NULL
    )
);

-- ================================================================
-- 4. SUBMISSION PARENT TABLE
-- ================================================================

-- SUBMISSIONS stores shared ownership, anonymity and workflow state.
CREATE TABLE submissions (
    submission_id       BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id             BIGINT NOT NULL,
    company_id          BIGINT NOT NULL,
    submission_type     VARCHAR(10) NOT NULL,
    is_anonymous        INTEGER DEFAULT 1 NOT NULL,
    submission_status   VARCHAR(10) DEFAULT 'PENDING' NOT NULL,
    verification_status VARCHAR(10) DEFAULT 'UNVERIFIED' NOT NULL,
    submitted_at        TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    approved_at         TIMESTAMPTZ,
    updated_at          TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_submissions PRIMARY KEY (submission_id),
    CONSTRAINT fk_submissions_user FOREIGN KEY (user_id)
        REFERENCES users (user_id),
    CONSTRAINT fk_submissions_company FOREIGN KEY (company_id)
        REFERENCES companies (company_id),
    CONSTRAINT ck_submissions_type CHECK (submission_type IN ('SALARY', 'REVIEW', 'INTERVIEW')),
    CONSTRAINT ck_submissions_anonymous CHECK (is_anonymous IN (0, 1)),
    CONSTRAINT ck_submissions_status CHECK (submission_status IN ('PENDING', 'APPROVED', 'FLAGGED', 'REJECTED')),
    CONSTRAINT ck_submissions_verify CHECK (verification_status IN ('VERIFIED', 'UNVERIFIED', 'PENDING', 'REJECTED')),
    CONSTRAINT ck_submissions_approved_at CHECK (
        (submission_status = 'APPROVED' AND approved_at IS NOT NULL)
        OR
        (submission_status <> 'APPROVED' AND approved_at IS NULL)
    )
);

-- ================================================================
-- 5. SUBMISSION SUBTYPE TABLES
-- ================================================================

-- SALARY_SUBMISSIONS extends one parent submission with salary details.
CREATE TABLE salary_submissions (
    submission_id           BIGINT,
    role_id                 BIGINT NOT NULL,
    base_salary             NUMERIC(12,2) NOT NULL,
    additional_compensation NUMERIC(12,2),
    currency                VARCHAR(3) DEFAULT 'BDT' NOT NULL,
    pay_period              VARCHAR(10) NOT NULL,
    years_of_experience     NUMERIC(4,1) NOT NULL,
    employment_type         VARCHAR(15) NOT NULL,
    work_mode               VARCHAR(10) NOT NULL,
    salary_year             INTEGER NOT NULL,
    CONSTRAINT pk_salary_submissions PRIMARY KEY (submission_id),
    CONSTRAINT fk_salary_submission FOREIGN KEY (submission_id)
        REFERENCES submissions (submission_id) ON DELETE CASCADE,
    CONSTRAINT fk_salary_role FOREIGN KEY (role_id)
        REFERENCES job_roles (role_id),
    CONSTRAINT ck_salary_base CHECK (base_salary > 0 AND base_salary <= 9999999999.99),
    CONSTRAINT ck_salary_additional CHECK (additional_compensation IS NULL OR additional_compensation >= 0),
    CONSTRAINT ck_salary_currency CHECK (LENGTH(currency) = 3 AND currency = UPPER(currency)),
    CONSTRAINT ck_salary_period CHECK (pay_period IN ('MONTHLY', 'YEARLY')),
    CONSTRAINT ck_salary_experience CHECK (years_of_experience BETWEEN 0 AND 60),
    CONSTRAINT ck_salary_employment CHECK (employment_type IN ('FULL_TIME', 'PART_TIME', 'CONTRACT', 'INTERN')),
    CONSTRAINT ck_salary_work_mode CHECK (work_mode IN ('ONSITE', 'HYBRID', 'REMOTE')),
    CONSTRAINT ck_salary_year CHECK (salary_year BETWEEN 2000 AND 2100)
);

-- COMPANY_REVIEWS extends one parent submission with workplace feedback.
CREATE TABLE company_reviews (
    submission_id            BIGINT,
    role_id                  BIGINT,
    review_title             VARCHAR(200) NOT NULL,
    overall_rating           NUMERIC(2,1) NOT NULL,
    work_life_balance_rating NUMERIC(2,1) NOT NULL,
    career_growth_rating     NUMERIC(2,1) NOT NULL,
    management_rating        NUMERIC(2,1) NOT NULL,
    culture_rating           NUMERIC(2,1) NOT NULL,
    pros                     TEXT NOT NULL,
    cons                     TEXT NOT NULL,
    advice_to_management     TEXT,
    employment_status        VARCHAR(10) NOT NULL,
    review_date              DATE NOT NULL,
    CONSTRAINT pk_company_reviews PRIMARY KEY (submission_id),
    CONSTRAINT fk_review_submission FOREIGN KEY (submission_id)
        REFERENCES submissions (submission_id) ON DELETE CASCADE,
    CONSTRAINT fk_review_role FOREIGN KEY (role_id)
        REFERENCES job_roles (role_id),
    CONSTRAINT ck_review_title CHECK (TRIM(review_title) <> ''),
    CONSTRAINT ck_review_overall CHECK (overall_rating BETWEEN 1 AND 5),
    CONSTRAINT ck_review_work_life CHECK (work_life_balance_rating BETWEEN 1 AND 5),
    CONSTRAINT ck_review_growth CHECK (career_growth_rating BETWEEN 1 AND 5),
    CONSTRAINT ck_review_management CHECK (management_rating BETWEEN 1 AND 5),
    CONSTRAINT ck_review_culture CHECK (culture_rating BETWEEN 1 AND 5),
    CONSTRAINT ck_review_pros CHECK (LENGTH(pros) > 0),
    CONSTRAINT ck_review_cons CHECK (LENGTH(cons) > 0),
    CONSTRAINT ck_review_employment CHECK (employment_status IN ('CURRENT', 'FORMER'))
);

-- INTERVIEW_EXPERIENCES extends one parent submission with interview details.
CREATE TABLE interview_experiences (
    submission_id       BIGINT,
    role_id             BIGINT NOT NULL,
    interview_date      DATE NOT NULL,
    difficulty_level    VARCHAR(10) NOT NULL,
    rounds_count        INTEGER NOT NULL,
    interview_mode      VARCHAR(10) NOT NULL,
    result_status       VARCHAR(10) NOT NULL,
    duration_days       INTEGER NOT NULL,
    process_description TEXT NOT NULL,
    questions_summary   TEXT,
    CONSTRAINT pk_interview_experiences PRIMARY KEY (submission_id),
    CONSTRAINT fk_interview_submission FOREIGN KEY (submission_id)
        REFERENCES submissions (submission_id) ON DELETE CASCADE,
    CONSTRAINT fk_interview_role FOREIGN KEY (role_id)
        REFERENCES job_roles (role_id),
    CONSTRAINT ck_interview_difficulty CHECK (difficulty_level IN ('EASY', 'MEDIUM', 'HARD')),
    CONSTRAINT ck_interview_rounds CHECK (rounds_count BETWEEN 1 AND 20),
    CONSTRAINT ck_interview_mode CHECK (interview_mode IN ('ONLINE', 'ONSITE', 'HYBRID')),
    CONSTRAINT ck_interview_result CHECK (result_status IN ('OFFERED', 'REJECTED', 'PENDING', 'WITHDREW')),
    CONSTRAINT ck_interview_duration CHECK (duration_days BETWEEN 0 AND 365),
    CONSTRAINT ck_interview_process CHECK (LENGTH(process_description) > 0)
);

-- ================================================================
-- 6. REPORTING AND MODERATION
-- ================================================================

-- REPORTS stores user complaints and their resolution workflow.
CREATE TABLE reports (
    report_id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    reporter_user_id   BIGINT NOT NULL,
    submission_id      BIGINT NOT NULL,
    reason_category    VARCHAR(15) NOT NULL,
    report_description VARCHAR(1000),
    report_status      VARCHAR(10) DEFAULT 'OPEN' NOT NULL,
    reported_at        TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    resolved_at        TIMESTAMPTZ,
    resolution_note    VARCHAR(1000),
    resolved_by        BIGINT,
    CONSTRAINT pk_reports PRIMARY KEY (report_id),
    CONSTRAINT uk_reports_reporter_submission UNIQUE (reporter_user_id, submission_id),
    CONSTRAINT fk_reports_reporter FOREIGN KEY (reporter_user_id)
        REFERENCES users (user_id),
    CONSTRAINT fk_reports_submission FOREIGN KEY (submission_id)
        REFERENCES submissions (submission_id) ON DELETE CASCADE,
    CONSTRAINT fk_reports_resolver FOREIGN KEY (resolved_by)
        REFERENCES users (user_id),
    CONSTRAINT ck_reports_reason CHECK (reason_category IN ('FAKE_DATA', 'DEFAMATION', 'SPAM', 'PRIVACY', 'OTHER')),
    CONSTRAINT ck_reports_status CHECK (report_status IN ('OPEN', 'REVIEWING', 'RESOLVED', 'DISMISSED')),
    CONSTRAINT ck_reports_resolution CHECK (
        (report_status IN ('OPEN', 'REVIEWING') AND resolved_at IS NULL AND resolved_by IS NULL)
        OR
        (report_status IN ('RESOLVED', 'DISMISSED') AND resolved_at IS NOT NULL AND resolved_by IS NOT NULL)
    )
);

-- MODERATION_ACTIONS stores append-only submission moderation history.
CREATE TABLE moderation_actions (
    action_id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    submission_id     BIGINT NOT NULL,
    moderator_user_id BIGINT NOT NULL,
    action_type       VARCHAR(15) NOT NULL,
    previous_status   VARCHAR(10),
    new_status        VARCHAR(10) NOT NULL,
    action_note       VARCHAR(1000),
    action_at         TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_moderation_actions PRIMARY KEY (action_id),
    CONSTRAINT fk_mod_actions_submission FOREIGN KEY (submission_id)
        REFERENCES submissions (submission_id) ON DELETE CASCADE,
    CONSTRAINT fk_mod_actions_moderator FOREIGN KEY (moderator_user_id)
        REFERENCES users (user_id),
    CONSTRAINT ck_mod_actions_type CHECK (action_type IN ('APPROVE', 'REJECT', 'FLAG', 'UNFLAG', 'EDIT_STATUS')),
    CONSTRAINT ck_mod_actions_previous CHECK (previous_status IS NULL OR previous_status IN ('PENDING', 'APPROVED', 'FLAGGED', 'REJECTED')),
    CONSTRAINT ck_mod_actions_new CHECK (new_status IN ('PENDING', 'APPROVED', 'FLAGGED', 'REJECTED'))
);

-- ================================================================
-- 7. COMPANY REPRESENTATIVES
-- ================================================================

-- COMPANY_REPRESENTATIVES binds one account to one company with an
-- administrator-controlled lifecycle. Public registration can never write here.
CREATE TABLE company_representatives (
    assignment_id     BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id           BIGINT NOT NULL,
    company_id        BIGINT NOT NULL,
    job_title         VARCHAR(120),
    assignment_status VARCHAR(10) DEFAULT 'PENDING' NOT NULL,
    request_note      VARCHAR(1000),
    decision_note     VARCHAR(1000),
    approved_by       BIGINT,
    approved_at       TIMESTAMPTZ,
    revoked_by        BIGINT,
    revoked_at        TIMESTAMPTZ,
    created_at        TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at        TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_company_representatives PRIMARY KEY (assignment_id),
    CONSTRAINT fk_company_rep_user FOREIGN KEY (user_id)
        REFERENCES users (user_id) ON DELETE CASCADE,
    CONSTRAINT fk_company_rep_company FOREIGN KEY (company_id)
        REFERENCES companies (company_id) ON DELETE RESTRICT,
    CONSTRAINT fk_company_rep_approver FOREIGN KEY (approved_by)
        REFERENCES users (user_id),
    CONSTRAINT fk_company_rep_revoker FOREIGN KEY (revoked_by)
        REFERENCES users (user_id),
    CONSTRAINT ck_company_rep_status
        CHECK (assignment_status IN ('PENDING', 'ACTIVE', 'REJECTED', 'REVOKED')),
    CONSTRAINT ck_company_rep_job_title
        CHECK (job_title IS NULL OR TRIM(job_title) <> ''),
    CONSTRAINT ck_company_rep_approval CHECK (
        (assignment_status = 'PENDING' AND approved_by IS NULL AND approved_at IS NULL)
        OR
        (assignment_status IN ('ACTIVE', 'REVOKED') AND approved_by IS NOT NULL AND approved_at IS NOT NULL)
        OR
        (assignment_status = 'REJECTED' AND approved_by IS NULL AND approved_at IS NULL)
    ),
    CONSTRAINT ck_company_rep_revocation CHECK (
        (assignment_status = 'REVOKED' AND revoked_by IS NOT NULL AND revoked_at IS NOT NULL)
        OR
        (assignment_status <> 'REVOKED' AND revoked_by IS NULL AND revoked_at IS NULL)
    ),
    CONSTRAINT ck_company_rep_decision_note CHECK (
        assignment_status NOT IN ('REJECTED', 'REVOKED') OR decision_note IS NOT NULL
    )
);

-- REPRESENTATIVE_ASSIGNMENT_ACTIONS stores append-only assignment history.
CREATE TABLE representative_assignment_actions (
    action_id       BIGINT GENERATED BY DEFAULT AS IDENTITY,
    assignment_id   BIGINT NOT NULL,
    actor_user_id   BIGINT NOT NULL,
    action_type     VARCHAR(10) NOT NULL,
    previous_status VARCHAR(10),
    new_status      VARCHAR(10) NOT NULL,
    action_note     VARCHAR(1000),
    action_at       TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_representative_assignment_actions PRIMARY KEY (action_id),
    CONSTRAINT fk_rep_action_assignment FOREIGN KEY (assignment_id)
        REFERENCES company_representatives (assignment_id) ON DELETE RESTRICT,
    CONSTRAINT fk_rep_action_actor FOREIGN KEY (actor_user_id)
        REFERENCES users (user_id),
    CONSTRAINT ck_rep_action_type
        CHECK (action_type IN ('REQUEST', 'APPROVE', 'REJECT', 'REVOKE')),
    CONSTRAINT ck_rep_action_previous
        CHECK (previous_status IS NULL OR previous_status IN ('PENDING', 'ACTIVE', 'REJECTED', 'REVOKED')),
    CONSTRAINT ck_rep_action_new
        CHECK (new_status IN ('PENDING', 'ACTIVE', 'REJECTED', 'REVOKED'))
);

-- ================================================================
-- 8. JOBS AND APPLICATIONS
-- ================================================================

-- JOB_POSTINGS is owned by one company and created inside a representative scope.
CREATE TABLE job_postings (
    job_id               BIGINT GENERATED BY DEFAULT AS IDENTITY,
    company_id           BIGINT NOT NULL,
    created_by_user_id   BIGINT NOT NULL,
    created_by_assignment_id BIGINT,
    role_id              BIGINT,
    title                VARCHAR(160) NOT NULL,
    description          TEXT NOT NULL,
    requirements         TEXT,
    location             VARCHAR(120) NOT NULL,
    employment_type      VARCHAR(15) NOT NULL,
    work_mode            VARCHAR(10) NOT NULL,
    salary_min           NUMERIC(12,2),
    salary_max           NUMERIC(12,2),
    salary_currency      VARCHAR(3),
    salary_period        VARCHAR(10),
    application_deadline DATE NOT NULL,
    job_status           VARCHAR(10) DEFAULT 'DRAFT' NOT NULL,
    access_level         VARCHAR(10) DEFAULT 'FREE' NOT NULL,
    published_at         TIMESTAMPTZ,
    closed_at            TIMESTAMPTZ,
    created_at           TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at           TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_job_postings PRIMARY KEY (job_id),
    CONSTRAINT fk_job_company FOREIGN KEY (company_id)
        REFERENCES companies (company_id) ON DELETE RESTRICT,
    CONSTRAINT fk_job_creator FOREIGN KEY (created_by_user_id)
        REFERENCES users (user_id),
    CONSTRAINT fk_job_assignment FOREIGN KEY (created_by_assignment_id)
        REFERENCES company_representatives (assignment_id) ON DELETE SET NULL,
    CONSTRAINT fk_job_role FOREIGN KEY (role_id)
        REFERENCES job_roles (role_id),
    CONSTRAINT ck_job_title CHECK (TRIM(title) <> ''),
    CONSTRAINT ck_job_description CHECK (LENGTH(TRIM(description)) >= 20),
    CONSTRAINT ck_job_location CHECK (TRIM(location) <> ''),
    CONSTRAINT ck_job_employment_type
        CHECK (employment_type IN ('FULL_TIME', 'PART_TIME', 'CONTRACT', 'INTERN')),
    CONSTRAINT ck_job_work_mode CHECK (work_mode IN ('ONSITE', 'HYBRID', 'REMOTE')),
    CONSTRAINT ck_job_status CHECK (job_status IN ('DRAFT', 'PUBLISHED', 'CLOSED', 'ARCHIVED')),
    CONSTRAINT ck_job_access_level CHECK (access_level IN ('FREE', 'PREMIUM')),
    CONSTRAINT ck_job_salary_range CHECK (
        (salary_min IS NULL AND salary_max IS NULL AND salary_currency IS NULL AND salary_period IS NULL)
        OR
        (salary_min IS NOT NULL AND salary_max IS NOT NULL
            AND salary_currency IS NOT NULL AND salary_period IS NOT NULL
            AND salary_min > 0 AND salary_max >= salary_min
            AND salary_max <= 9999999999.99)
    ),
    CONSTRAINT ck_job_salary_currency CHECK (
        salary_currency IS NULL
        OR (LENGTH(salary_currency) = 3 AND salary_currency = UPPER(salary_currency))
    ),
    CONSTRAINT ck_job_salary_period CHECK (
        salary_period IS NULL OR salary_period IN ('MONTHLY', 'YEARLY')
    ),
    CONSTRAINT ck_job_published_at CHECK (
        (job_status = 'DRAFT' AND published_at IS NULL)
        OR
        (job_status <> 'DRAFT' AND published_at IS NOT NULL)
    ),
    CONSTRAINT ck_job_closed_at CHECK (
        (job_status IN ('CLOSED', 'ARCHIVED') AND closed_at IS NOT NULL)
        OR
        (job_status IN ('DRAFT', 'PUBLISHED') AND closed_at IS NULL)
    )
);

-- JOB_APPLICATIONS allows exactly one application per account and job.
-- Saple stores no uploaded documents and never fetches applicant-supplied URLs.
CREATE TABLE job_applications (
    application_id     BIGINT GENERATED BY DEFAULT AS IDENTITY,
    job_id             BIGINT NOT NULL,
    applicant_user_id  BIGINT NOT NULL,
    cover_letter       TEXT NOT NULL,
    application_status VARCHAR(15) DEFAULT 'SUBMITTED' NOT NULL,
    submitted_at       TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at         TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    reviewed_by        BIGINT,
    reviewed_at        TIMESTAMPTZ,
    CONSTRAINT pk_job_applications PRIMARY KEY (application_id),
    CONSTRAINT uk_job_applications_once UNIQUE (job_id, applicant_user_id),
    CONSTRAINT fk_application_job FOREIGN KEY (job_id)
        REFERENCES job_postings (job_id) ON DELETE RESTRICT,
    CONSTRAINT fk_application_applicant FOREIGN KEY (applicant_user_id)
        REFERENCES users (user_id),
    CONSTRAINT fk_application_reviewer FOREIGN KEY (reviewed_by)
        REFERENCES users (user_id),
    CONSTRAINT ck_application_cover_letter
        CHECK (LENGTH(TRIM(cover_letter)) BETWEEN 30 AND 4000),
    CONSTRAINT ck_application_status CHECK (application_status IN (
        'SUBMITTED', 'UNDER_REVIEW', 'SHORTLISTED', 'REJECTED', 'WITHDRAWN', 'ACCEPTED'
    )),
    CONSTRAINT ck_application_review CHECK (
        (application_status IN ('SUBMITTED', 'WITHDRAWN') AND reviewed_by IS NULL AND reviewed_at IS NULL)
        OR
        (application_status IN ('UNDER_REVIEW', 'SHORTLISTED', 'REJECTED', 'ACCEPTED')
            AND reviewed_by IS NOT NULL AND reviewed_at IS NOT NULL)
    )
);

-- JOB_APPLICATION_STATUS_HISTORY stores append-only application decisions.
CREATE TABLE job_application_status_history (
    history_id      BIGINT GENERATED BY DEFAULT AS IDENTITY,
    application_id  BIGINT NOT NULL,
    actor_user_id   BIGINT NOT NULL,
    previous_status VARCHAR(15),
    new_status      VARCHAR(15) NOT NULL,
    action_note     VARCHAR(1000),
    action_at       TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_job_application_status_history PRIMARY KEY (history_id),
    CONSTRAINT fk_application_history_application FOREIGN KEY (application_id)
        REFERENCES job_applications (application_id) ON DELETE RESTRICT,
    CONSTRAINT fk_application_history_actor FOREIGN KEY (actor_user_id)
        REFERENCES users (user_id),
    CONSTRAINT ck_application_history_previous CHECK (
        previous_status IS NULL OR previous_status IN (
            'SUBMITTED', 'UNDER_REVIEW', 'SHORTLISTED', 'REJECTED', 'WITHDRAWN', 'ACCEPTED'
        )
    ),
    CONSTRAINT ck_application_history_new CHECK (new_status IN (
        'SUBMITTED', 'UNDER_REVIEW', 'SHORTLISTED', 'REJECTED', 'WITHDRAWN', 'ACCEPTED'
    ))
);

-- JOB_APPLICATION_RESUMES keeps an applicant's optional PDF resume, at most
-- one per application, apart from the application row so ordinary lists never
-- read the file. It is private: served only through the authorised resume
-- endpoints, never from a public bucket.
CREATE TABLE job_application_resumes (
    application_id     BIGINT NOT NULL,
    original_file_name VARCHAR(255) NOT NULL,
    mime_type          VARCHAR(100) NOT NULL,
    file_size_bytes    INTEGER NOT NULL,
    sha256_hex         CHAR(64) NOT NULL,
    pdf_data           BYTEA NOT NULL,
    uploaded_at        TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at         TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_job_application_resumes PRIMARY KEY (application_id),
    CONSTRAINT fk_job_application_resume_application FOREIGN KEY (application_id)
        REFERENCES job_applications (application_id) ON DELETE CASCADE,
    CONSTRAINT ck_job_application_resume_name CHECK (TRIM(original_file_name) <> ''),
    CONSTRAINT ck_job_application_resume_mime CHECK (mime_type = 'application/pdf'),
    CONSTRAINT ck_job_application_resume_size CHECK (file_size_bytes > 0 AND file_size_bytes <= 2097152),
    CONSTRAINT ck_job_application_resume_length CHECK (OCTET_LENGTH(pdf_data) = file_size_bytes),
    CONSTRAINT ck_job_application_resume_sha256 CHECK (sha256_hex ~ '^[0-9a-f]{64}$')
);

-- ================================================================
-- 9. ANNOUNCEMENTS AND PRIVATE NOTIFICATIONS
-- ================================================================

-- ANNOUNCEMENTS holds public, admin-managed, plain-text notices.
CREATE TABLE announcements (
    announcement_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    title           VARCHAR(160) NOT NULL,
    message         VARCHAR(600) NOT NULL,
    severity        VARCHAR(10) DEFAULT 'INFO' NOT NULL,
    is_dismissible  BOOLEAN DEFAULT TRUE NOT NULL,
    is_active       BOOLEAN DEFAULT TRUE NOT NULL,
    starts_at       TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ends_at         TIMESTAMPTZ,
    created_by      BIGINT NOT NULL,
    created_at      TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at      TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_announcements PRIMARY KEY (announcement_id),
    CONSTRAINT fk_announcements_author FOREIGN KEY (created_by)
        REFERENCES users (user_id),
    CONSTRAINT ck_announcements_title CHECK (TRIM(title) <> ''),
    CONSTRAINT ck_announcements_message CHECK (TRIM(message) <> ''),
    CONSTRAINT ck_announcements_severity CHECK (severity IN ('INFO', 'WARNING', 'CRITICAL')),
    CONSTRAINT ck_announcements_window CHECK (ends_at IS NULL OR ends_at > starts_at),
    CONSTRAINT ck_announcements_plain_text CHECK (
        title !~ '[<>]' AND message !~ '[<>]'
    )
);

-- NOTIFICATIONS is always private to exactly one account.
CREATE TABLE notifications (
    notification_id     BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id             BIGINT NOT NULL,
    notification_type   VARCHAR(30) NOT NULL,
    title               VARCHAR(160) NOT NULL,
    message             VARCHAR(600) NOT NULL,
    related_entity_type VARCHAR(30),
    related_entity_id   BIGINT,
    read_at             TIMESTAMPTZ,
    created_at          TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_notifications PRIMARY KEY (notification_id),
    CONSTRAINT fk_notifications_user FOREIGN KEY (user_id)
        REFERENCES users (user_id) ON DELETE CASCADE,
    CONSTRAINT ck_notifications_title CHECK (TRIM(title) <> ''),
    CONSTRAINT ck_notifications_message CHECK (TRIM(message) <> ''),
    CONSTRAINT ck_notifications_type CHECK (notification_type IN (
        'VERIFICATION_DECISION',
        'SUBMISSION_DECISION',
        'REPRESENTATIVE_DECISION',
        'REPORT_OUTCOME',
        'APPLICATION_RECEIVED',
        'APPLICATION_STATUS',
        'JOB_CLOSED',
        'SECURITY_EVENT',
        'PREMIUM_TRIAL_STARTED',
        'PREMIUM_PURCHASE'
    )),
    CONSTRAINT ck_notifications_entity CHECK (
        (related_entity_type IS NULL AND related_entity_id IS NULL)
        OR
        (related_entity_type IN (
            'SUBMISSION', 'VERIFICATION', 'JOB', 'APPLICATION', 'ASSIGNMENT', 'REPORT', 'ACCOUNT'
        ) AND related_entity_id IS NOT NULL AND related_entity_id > 0)
    ),
    CONSTRAINT ck_notifications_plain_text CHECK (
        title !~ '[<>]' AND message !~ '[<>]'
    )
);

-- ================================================================
-- 10. SUPPORTING INDEXES
-- ================================================================

-- Private direct messages exist only in the cloud installation. A local demo
-- database may have the table, but the API never reads or writes it there.
CREATE TABLE direct_messages (
    message_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    sender_user_id BIGINT NOT NULL,
    recipient_user_id BIGINT NOT NULL,
    message_body VARCHAR(2000),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    edited_at TIMESTAMPTZ,
    deleted_at TIMESTAMPTZ,
    read_at TIMESTAMPTZ,
    CONSTRAINT pk_direct_messages PRIMARY KEY (message_id),
    CONSTRAINT fk_direct_messages_sender FOREIGN KEY (sender_user_id)
        REFERENCES users (user_id) ON DELETE CASCADE,
    CONSTRAINT fk_direct_messages_recipient FOREIGN KEY (recipient_user_id)
        REFERENCES users (user_id) ON DELETE CASCADE,
    CONSTRAINT ck_direct_messages_distinct_users CHECK (sender_user_id <> recipient_user_id),
    CONSTRAINT ck_direct_messages_live_body CHECK (deleted_at IS NOT NULL OR (message_body IS NOT NULL AND LENGTH(TRIM(message_body)) > 0))
);
CREATE INDEX ix_direct_messages_sender_recipient ON direct_messages (sender_user_id, recipient_user_id, message_id DESC);
CREATE INDEX ix_direct_messages_recipient_sender ON direct_messages (recipient_user_id, sender_user_id, message_id DESC);
CREATE INDEX ix_direct_messages_unread ON direct_messages (recipient_user_id, read_at, message_id DESC);

-- ================================================================
-- PREMIUM SUBSCRIPTIONS
-- ================================================================

-- PREMIUM_PLANS is the server-side price list. Checkout always reads the
-- price from here; a price sent by a browser is never used.
CREATE TABLE premium_plans (
    plan_id       BIGINT GENERATED BY DEFAULT AS IDENTITY,
    plan_code     VARCHAR(30) NOT NULL,
    name          VARCHAR(80) NOT NULL,
    duration_days INTEGER NOT NULL,
    price_bdt     NUMERIC(10,2) NOT NULL,
    is_active     BOOLEAN DEFAULT TRUE NOT NULL,
    sort_order    INTEGER DEFAULT 0 NOT NULL,
    created_at    TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at    TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_premium_plans PRIMARY KEY (plan_id),
    CONSTRAINT uk_premium_plans_code UNIQUE (plan_code),
    CONSTRAINT ck_premium_plans_code CHECK (plan_code ~ '^[A-Z0-9_]{2,30}$'),
    CONSTRAINT ck_premium_plans_name CHECK (TRIM(name) <> ''),
    CONSTRAINT ck_premium_plans_duration CHECK (duration_days > 0),
    CONSTRAINT ck_premium_plans_price CHECK (price_bdt >= 0)
);

-- PREMIUM_TRIAL_CLAIMS keeps permanent proof of the one free trial. The
-- primary key on user_id is the hard guarantee: a second row for the same
-- account cannot exist, however many requests arrive at once.
CREATE TABLE premium_trial_claims (
    user_id    BIGINT NOT NULL,
    claimed_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    starts_at  TIMESTAMPTZ NOT NULL,
    ends_at    TIMESTAMPTZ NOT NULL,
    CONSTRAINT pk_premium_trial_claims PRIMARY KEY (user_id),
    CONSTRAINT fk_premium_trial_user FOREIGN KEY (user_id)
        REFERENCES users (user_id),
    CONSTRAINT ck_premium_trial_period CHECK (ends_at > starts_at)
);

-- PREMIUM_PROMO_CODES are admin-managed discount (promo or referral) codes.
CREATE TABLE premium_promo_codes (
    promo_code_id        BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code                 VARCHAR(40) NOT NULL,
    description          VARCHAR(300),
    discount_type        VARCHAR(10) NOT NULL,
    discount_value       NUMERIC(10,2) NOT NULL,
    max_discount_bdt     NUMERIC(10,2),
    applicable_plan_code VARCHAR(30),
    max_redemptions      INTEGER,
    per_user_limit       INTEGER DEFAULT 1 NOT NULL,
    valid_from           TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    valid_until          TIMESTAMPTZ,
    is_active            BOOLEAN DEFAULT TRUE NOT NULL,
    created_by           BIGINT,
    created_at           TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at           TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_premium_promo_codes PRIMARY KEY (promo_code_id),
    CONSTRAINT uk_premium_promo_code UNIQUE (code),
    CONSTRAINT fk_premium_promo_plan FOREIGN KEY (applicable_plan_code)
        REFERENCES premium_plans (plan_code),
    CONSTRAINT fk_premium_promo_creator FOREIGN KEY (created_by)
        REFERENCES users (user_id),
    CONSTRAINT ck_premium_promo_code CHECK (code ~ '^[A-Z0-9_-]{3,40}$'),
    CONSTRAINT ck_premium_promo_type CHECK (discount_type IN ('PERCENT', 'FIXED')),
    CONSTRAINT ck_premium_promo_value CHECK (
        discount_value > 0 AND (discount_type <> 'PERCENT' OR discount_value <= 100)
    ),
    CONSTRAINT ck_premium_promo_max_discount CHECK (max_discount_bdt IS NULL OR max_discount_bdt > 0),
    CONSTRAINT ck_premium_promo_max_redemptions CHECK (max_redemptions IS NULL OR max_redemptions > 0),
    CONSTRAINT ck_premium_promo_per_user CHECK (per_user_limit > 0),
    CONSTRAINT ck_premium_promo_window CHECK (valid_until IS NULL OR valid_until > valid_from)
);

-- PREMIUM_PAYMENTS records every checkout attempt. It is created before the
-- gateway is contacted, and only verified settlement marks it SUCCEEDED.
CREATE TABLE premium_payments (
    payment_id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
    public_id              UUID DEFAULT gen_random_uuid() NOT NULL,
    user_id                BIGINT NOT NULL,
    plan_id                BIGINT NOT NULL,
    promo_code_id          BIGINT,
    base_amount_bdt        NUMERIC(10,2) NOT NULL,
    discount_amount_bdt    NUMERIC(10,2) DEFAULT 0 NOT NULL,
    final_amount_bdt       NUMERIC(10,2) NOT NULL,
    currency               VARCHAR(3) DEFAULT 'BDT' NOT NULL,
    gateway                VARCHAR(30) DEFAULT 'SSLCOMMERZ' NOT NULL,
    gateway_session_key    VARCHAR(255),
    gateway_transaction_id VARCHAR(255),
    gateway_validation_id  VARCHAR(255),
    status                 VARCHAR(10) DEFAULT 'INITIATED' NOT NULL,
    initiated_at           TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    completed_at           TIMESTAMPTZ,
    created_at             TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at             TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_premium_payments PRIMARY KEY (payment_id),
    CONSTRAINT uk_premium_payments_public UNIQUE (public_id),
    CONSTRAINT fk_premium_payment_user FOREIGN KEY (user_id)
        REFERENCES users (user_id),
    CONSTRAINT fk_premium_payment_plan FOREIGN KEY (plan_id)
        REFERENCES premium_plans (plan_id),
    CONSTRAINT fk_premium_payment_promo FOREIGN KEY (promo_code_id)
        REFERENCES premium_promo_codes (promo_code_id),
    CONSTRAINT ck_premium_payment_amounts CHECK (
        base_amount_bdt >= 0 AND discount_amount_bdt >= 0 AND final_amount_bdt >= 0
        AND final_amount_bdt = base_amount_bdt - discount_amount_bdt
    ),
    CONSTRAINT ck_premium_payment_currency CHECK (currency = 'BDT'),
    CONSTRAINT ck_premium_payment_status CHECK (
        status IN ('INITIATED', 'PENDING', 'SUCCEEDED', 'FAILED', 'CANCELLED', 'REFUNDED')
    ),
    CONSTRAINT ck_premium_payment_completion CHECK (
        (status IN ('INITIATED', 'PENDING') AND completed_at IS NULL)
        OR (status NOT IN ('INITIATED', 'PENDING') AND completed_at IS NOT NULL)
    )
);

-- PREMIUM_ACCESS_PERIODS holds paid access. Each verified payment grants
-- exactly one period (the unique payment_id), so a repeated callback can
-- never add time twice. Premium is never stored as a flag on users.
CREATE TABLE premium_access_periods (
    access_id   BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id     BIGINT NOT NULL,
    source_type VARCHAR(10) DEFAULT 'PAID' NOT NULL,
    plan_id     BIGINT NOT NULL,
    payment_id  BIGINT NOT NULL,
    starts_at   TIMESTAMPTZ NOT NULL,
    ends_at     TIMESTAMPTZ NOT NULL,
    created_at  TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_premium_access_periods PRIMARY KEY (access_id),
    CONSTRAINT uk_premium_access_payment UNIQUE (payment_id),
    CONSTRAINT fk_premium_access_user FOREIGN KEY (user_id)
        REFERENCES users (user_id),
    CONSTRAINT fk_premium_access_plan FOREIGN KEY (plan_id)
        REFERENCES premium_plans (plan_id),
    CONSTRAINT fk_premium_access_payment FOREIGN KEY (payment_id)
        REFERENCES premium_payments (payment_id),
    CONSTRAINT ck_premium_access_source CHECK (source_type = 'PAID'),
    CONSTRAINT ck_premium_access_period CHECK (ends_at > starts_at)
);

-- PREMIUM_PROMO_REDEMPTIONS tracks each code use: reserved at checkout,
-- redeemed on verified payment, released on failure or expiry.
CREATE TABLE premium_promo_redemptions (
    redemption_id       BIGINT GENERATED BY DEFAULT AS IDENTITY,
    promo_code_id       BIGINT NOT NULL,
    user_id             BIGINT NOT NULL,
    payment_id          BIGINT NOT NULL,
    discount_amount_bdt NUMERIC(10,2) NOT NULL,
    status              VARCHAR(10) DEFAULT 'RESERVED' NOT NULL,
    reserved_at         TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    redeemed_at         TIMESTAMPTZ,
    released_at         TIMESTAMPTZ,
    CONSTRAINT pk_premium_promo_redemptions PRIMARY KEY (redemption_id),
    CONSTRAINT uk_premium_redemption_payment UNIQUE (payment_id),
    CONSTRAINT fk_premium_redemption_code FOREIGN KEY (promo_code_id)
        REFERENCES premium_promo_codes (promo_code_id),
    CONSTRAINT fk_premium_redemption_user FOREIGN KEY (user_id)
        REFERENCES users (user_id),
    CONSTRAINT fk_premium_redemption_payment FOREIGN KEY (payment_id)
        REFERENCES premium_payments (payment_id),
    CONSTRAINT ck_premium_redemption_discount CHECK (discount_amount_bdt >= 0),
    CONSTRAINT ck_premium_redemption_status CHECK (status IN ('RESERVED', 'REDEEMED', 'RELEASED')),
    CONSTRAINT ck_premium_redemption_state CHECK (
        (status = 'RESERVED' AND redeemed_at IS NULL AND released_at IS NULL)
        OR (status = 'REDEEMED' AND redeemed_at IS NOT NULL AND released_at IS NULL)
        OR (status = 'RELEASED' AND released_at IS NOT NULL AND redeemed_at IS NULL)
    )
);

-- PROFILE_VIEWS aggregates signed-in, non-self profile views per day.
-- Anonymous visitors are never recorded.
CREATE TABLE profile_views (
    profile_user_id BIGINT NOT NULL,
    viewer_user_id  BIGINT NOT NULL,
    view_date       DATE DEFAULT CURRENT_DATE NOT NULL,
    first_viewed_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    last_viewed_at  TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    view_count      INTEGER DEFAULT 1 NOT NULL,
    CONSTRAINT pk_profile_views PRIMARY KEY (profile_user_id, viewer_user_id, view_date),
    CONSTRAINT fk_profile_views_profile FOREIGN KEY (profile_user_id)
        REFERENCES users (user_id) ON DELETE CASCADE,
    CONSTRAINT fk_profile_views_viewer FOREIGN KEY (viewer_user_id)
        REFERENCES users (user_id) ON DELETE CASCADE,
    CONSTRAINT ck_profile_views_not_self CHECK (profile_user_id <> viewer_user_id),
    CONSTRAINT ck_profile_views_count CHECK (view_count > 0),
    CONSTRAINT ck_profile_views_order CHECK (last_viewed_at >= first_viewed_at)
);

-- PREMIUM_AI_USAGE counts Premium AI requests for daily limits. It stores
-- no prompt or resume text.
CREATE TABLE premium_ai_usage (
    usage_id      BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id       BIGINT NOT NULL,
    feature_type  VARCHAR(20) NOT NULL,
    model         VARCHAR(120),
    input_tokens  INTEGER,
    output_tokens INTEGER,
    created_at    TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_premium_ai_usage PRIMARY KEY (usage_id),
    CONSTRAINT fk_premium_ai_usage_user FOREIGN KEY (user_id)
        REFERENCES users (user_id) ON DELETE CASCADE,
    CONSTRAINT ck_premium_ai_feature CHECK (feature_type IN ('ADVANCED_CHAT', 'RESUME_GENERATION')),
    CONSTRAINT ck_premium_ai_tokens CHECK (
        (input_tokens IS NULL OR input_tokens >= 0) AND (output_tokens IS NULL OR output_tokens >= 0)
    )
);

CREATE INDEX ix_premium_payments_user ON premium_payments (user_id, created_at DESC);
CREATE INDEX ix_premium_payments_status ON premium_payments (status, created_at DESC);
CREATE INDEX ix_premium_access_user_end ON premium_access_periods (user_id, ends_at DESC);
CREATE INDEX ix_premium_redemptions_code ON premium_promo_redemptions (promo_code_id, status);
CREATE INDEX ix_premium_redemptions_user ON premium_promo_redemptions (promo_code_id, user_id, status);
CREATE INDEX ix_profile_views_profile ON profile_views (profile_user_id, last_viewed_at DESC);
CREATE INDEX ix_premium_ai_usage_user ON premium_ai_usage (user_id, feature_type, created_at DESC);
CREATE INDEX ix_job_postings_access ON job_postings (access_level);

-- The two plans. Prices are authoritative here, in BDT.
INSERT INTO premium_plans (plan_code, name, duration_days, price_bdt, sort_order) VALUES
    ('PREMIUM_1M', 'Premium 1 Month', 30, 120.00, 1),
    ('PREMIUM_3M', 'Premium 3 Months', 90, 300.00, 2)
ON CONFLICT (plan_code) DO NOTHING;


CREATE INDEX ix_password_reset_user_state
    ON password_reset_tokens (user_id, expires_at, used_at, revoked_at);
CREATE INDEX ix_companies_industry_city ON companies (industry, headquarters_city);
CREATE INDEX ix_company_benefits_benefit ON company_benefits (benefit_id);
CREATE INDEX ix_emp_verify_company_status ON employment_verifications (company_id, verification_status);
CREATE INDEX ix_emp_verify_employee ON employment_verifications (employee_id);
CREATE INDEX ix_emp_verify_reviewer ON employment_verifications (reviewed_by);
CREATE INDEX ix_emp_verify_scope_status
    ON employment_verifications (employee_id, company_id, role_id, verification_status);
CREATE INDEX ix_submissions_user ON submissions (user_id);
CREATE INDEX ix_submissions_company_status ON submissions (company_id, submission_status);
CREATE INDEX ix_submissions_verify_status ON submissions (verification_status);
CREATE INDEX ix_salary_role ON salary_submissions (role_id);
CREATE INDEX ix_review_role ON company_reviews (role_id);
CREATE INDEX ix_interview_role ON interview_experiences (role_id);
CREATE INDEX ix_reports_submission_status ON reports (submission_id, report_status);
CREATE INDEX ix_reports_resolver ON reports (resolved_by);
CREATE INDEX ix_mod_actions_submission_time ON moderation_actions (submission_id, action_at);
CREATE INDEX ix_mod_actions_moderator ON moderation_actions (moderator_user_id);
CREATE UNIQUE INDEX uk_company_rep_open_scope
    ON company_representatives (user_id, company_id)
    WHERE assignment_status IN ('PENDING', 'ACTIVE');
CREATE INDEX ix_company_rep_company_status
    ON company_representatives (company_id, assignment_status);
CREATE INDEX ix_company_rep_user_status
    ON company_representatives (user_id, assignment_status);
CREATE INDEX ix_company_rep_status_created
    ON company_representatives (assignment_status, created_at);
CREATE INDEX ix_rep_action_assignment_time
    ON representative_assignment_actions (assignment_id, action_at);
CREATE INDEX ix_rep_action_actor
    ON representative_assignment_actions (actor_user_id);
CREATE INDEX ix_job_company_status ON job_postings (company_id, job_status);
CREATE INDEX ix_job_status_deadline ON job_postings (job_status, application_deadline);
CREATE INDEX ix_job_role ON job_postings (role_id);
CREATE INDEX ix_job_creator ON job_postings (created_by_user_id);
CREATE INDEX ix_job_assignment ON job_postings (created_by_assignment_id);
CREATE INDEX ix_job_published_at ON job_postings (published_at DESC);
CREATE INDEX ix_application_job_status ON job_applications (job_id, application_status);
CREATE INDEX ix_application_applicant ON job_applications (applicant_user_id, submitted_at DESC);
CREATE INDEX ix_application_reviewer ON job_applications (reviewed_by);
CREATE INDEX ix_application_history_application
    ON job_application_status_history (application_id, action_at);
CREATE INDEX ix_application_history_actor
    ON job_application_status_history (actor_user_id);
CREATE INDEX ix_announcements_window ON announcements (is_active, starts_at, ends_at);
CREATE INDEX ix_announcements_author ON announcements (created_by);
CREATE INDEX ix_notifications_owner_time
    ON notifications (user_id, created_at DESC, notification_id DESC);
CREATE INDEX ix_notifications_unread ON notifications (user_id) WHERE read_at IS NULL;

-- ================================================================
-- 11. PUBLIC AND ANALYTICAL VIEWS
-- ================================================================

-- Public views omit account identity and private workflow information.
CREATE OR REPLACE VIEW vw_public_companies AS
SELECT company_id,
       company_name,
       industry,
       headquarters_city,
       country,
       website,
       company_size,
       description
FROM companies;

CREATE OR REPLACE VIEW vw_public_approved_reviews AS
SELECT s.submission_id,
       s.company_id,
       c.company_name,
       r.role_id,
       jr.role_name,
       r.review_title,
       r.overall_rating,
       r.work_life_balance_rating,
       r.career_growth_rating,
       r.management_rating,
       r.culture_rating,
       r.pros,
       r.cons,
       r.advice_to_management,
       r.employment_status,
       r.review_date,
       s.verification_status,
       s.submitted_at
FROM submissions s
JOIN company_reviews r ON r.submission_id = s.submission_id
JOIN companies c ON c.company_id = s.company_id
LEFT JOIN job_roles jr ON jr.role_id = r.role_id
WHERE s.submission_type = 'REVIEW'
  AND s.submission_status = 'APPROVED';

CREATE OR REPLACE VIEW vw_verified_salary_summary AS
SELECT s.company_id,
       c.company_name,
       ss.role_id,
       jr.role_name,
       ss.currency,
       ss.pay_period,
       MIN(ss.base_salary) AS minimum_salary,
       MAX(ss.base_salary) AS maximum_salary,
       ROUND(AVG(ss.base_salary), 2) AS average_salary,
       COUNT(*) AS contribution_count
FROM submissions s
JOIN salary_submissions ss ON ss.submission_id = s.submission_id
JOIN companies c ON c.company_id = s.company_id
JOIN job_roles jr ON jr.role_id = ss.role_id
WHERE s.submission_type = 'SALARY'
  AND s.submission_status = 'APPROVED'
  AND s.verification_status = 'VERIFIED'
GROUP BY s.company_id, c.company_name, ss.role_id, jr.role_name,
         ss.currency, ss.pay_period;

CREATE OR REPLACE VIEW vw_community_salary_summary AS
SELECT s.company_id,
       c.company_name,
       ss.role_id,
       jr.role_name,
       ss.currency,
       ss.pay_period,
       MIN(ss.base_salary) AS minimum_salary,
       MAX(ss.base_salary) AS maximum_salary,
       ROUND(AVG(ss.base_salary), 2) AS average_salary,
       COUNT(*) AS contribution_count
FROM submissions s
JOIN salary_submissions ss ON ss.submission_id = s.submission_id
JOIN companies c ON c.company_id = s.company_id
JOIN job_roles jr ON jr.role_id = ss.role_id
WHERE s.submission_type = 'SALARY'
  AND s.submission_status = 'APPROVED'
GROUP BY s.company_id, c.company_name, ss.role_id, jr.role_name,
         ss.currency, ss.pay_period;

-- Published, still-open jobs only. Draft, closed and archived rows never
-- appear, and no applicant or private representative data is exposed.
CREATE OR REPLACE VIEW vw_public_open_jobs AS
SELECT jp.job_id,
       jp.company_id,
       c.company_name,
       c.industry,
       jp.role_id,
       jr.role_name,
       jr.role_category,
       jp.title,
       jp.description,
       jp.requirements,
       jp.location,
       jp.employment_type,
       jp.work_mode,
       jp.salary_min,
       jp.salary_max,
       jp.salary_currency,
       jp.salary_period,
       jp.application_deadline,
       jp.published_at,
       jp.access_level
FROM job_postings jp
JOIN companies c ON c.company_id = jp.company_id
LEFT JOIN job_roles jr ON jr.role_id = jp.role_id
WHERE jp.job_status = 'PUBLISHED'
  AND jp.application_deadline >= CURRENT_DATE;

-- Express is the only application database client. Supabase browser roles
-- receive no direct table/view access when those roles exist.
DO $saple_security$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN
        REVOKE ALL ON ALL TABLES IN SCHEMA public FROM anon;
        REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM anon;
        ALTER DEFAULT PRIVILEGES IN SCHEMA public
            REVOKE ALL ON TABLES FROM anon;
        ALTER DEFAULT PRIVILEGES IN SCHEMA public
            REVOKE ALL ON SEQUENCES FROM anon;
    END IF;

    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN
        REVOKE ALL ON ALL TABLES IN SCHEMA public FROM authenticated;
        REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM authenticated;
        ALTER DEFAULT PRIVILEGES IN SCHEMA public
            REVOKE ALL ON TABLES FROM authenticated;
        ALTER DEFAULT PRIVILEGES IN SCHEMA public
            REVOKE ALL ON SEQUENCES FROM authenticated;
    END IF;
END
$saple_security$;


-- ===========================================================================
-- CSE216 final database features (identical to migrations/005_cse216_final_database_features.sql)
--
-- A fresh installation gets the same trigger, function and procedure that
-- migration 005 adds to an existing database.
-- ===========================================================================

-- ---------------------------------------------------------------------------
-- 1. Trigger: the database owns updated_at
--
-- Every table below already has updated_at, and the application sets it in
-- each UPDATE. Keeping the rule in the database means the column stays true
-- even for a write issued outside Express: a psql session, the Supabase SQL
-- editor, a future job, or a repository that forgets the column. The trigger
-- is BEFORE UPDATE, so it changes the row being written rather than issuing a
-- second write, and it cannot recurse.
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION saple_set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at := CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$;

COMMENT ON FUNCTION saple_set_updated_at() IS
    'Sets updated_at on the row being updated. Used by the trg_*_set_updated_at triggers.';

DROP TRIGGER IF EXISTS trg_users_set_updated_at ON users;
CREATE TRIGGER trg_users_set_updated_at
    BEFORE UPDATE ON users
    FOR EACH ROW EXECUTE FUNCTION saple_set_updated_at();

DROP TRIGGER IF EXISTS trg_companies_set_updated_at ON companies;
CREATE TRIGGER trg_companies_set_updated_at
    BEFORE UPDATE ON companies
    FOR EACH ROW EXECUTE FUNCTION saple_set_updated_at();

DROP TRIGGER IF EXISTS trg_submissions_set_updated_at ON submissions;
CREATE TRIGGER trg_submissions_set_updated_at
    BEFORE UPDATE ON submissions
    FOR EACH ROW EXECUTE FUNCTION saple_set_updated_at();

DROP TRIGGER IF EXISTS trg_company_representatives_set_updated_at ON company_representatives;
CREATE TRIGGER trg_company_representatives_set_updated_at
    BEFORE UPDATE ON company_representatives
    FOR EACH ROW EXECUTE FUNCTION saple_set_updated_at();

DROP TRIGGER IF EXISTS trg_job_postings_set_updated_at ON job_postings;
CREATE TRIGGER trg_job_postings_set_updated_at
    BEFORE UPDATE ON job_postings
    FOR EACH ROW EXECUTE FUNCTION saple_set_updated_at();

DROP TRIGGER IF EXISTS trg_job_applications_set_updated_at ON job_applications;
CREATE TRIGGER trg_job_applications_set_updated_at
    BEFORE UPDATE ON job_applications
    FOR EACH ROW EXECUTE FUNCTION saple_set_updated_at();

DROP TRIGGER IF EXISTS trg_announcements_set_updated_at ON announcements;
CREATE TRIGGER trg_announcements_set_updated_at
    BEFORE UPDATE ON announcements
    FOR EACH ROW EXECUTE FUNCTION saple_set_updated_at();

-- ---------------------------------------------------------------------------
-- 2. Function: one company's public statistics
--
-- Returns the figures the company page reports, computed from approved
-- submissions only. Each aggregate is its own scalar subquery, so joining
-- several one-to-many tables cannot multiply the counts. STABLE: it reads the
-- database and returns the same answer inside one statement.
--
-- Evaluation:  SELECT * FROM saple_company_insight_summary(<company_id>);
-- ---------------------------------------------------------------------------

DROP FUNCTION IF EXISTS saple_company_insight_summary(BIGINT);
CREATE FUNCTION saple_company_insight_summary(p_company_id BIGINT)
RETURNS TABLE (
    company_id            BIGINT,
    review_count          INTEGER,
    average_rating        NUMERIC(3, 2),
    approved_salary_count INTEGER,
    minimum_salary        NUMERIC(12, 2),
    maximum_salary        NUMERIC(12, 2),
    average_salary        NUMERIC(12, 2),
    interview_count       INTEGER,
    open_job_count        INTEGER
)
LANGUAGE sql
STABLE
AS $$
    SELECT
        c.company_id,
        (SELECT COUNT(*)::INTEGER
           FROM submissions s
           JOIN company_reviews cr ON cr.submission_id = s.submission_id
          WHERE s.company_id = c.company_id
            AND s.submission_status = 'APPROVED')                       AS review_count,
        (SELECT ROUND(AVG(cr.overall_rating), 2)::NUMERIC(3, 2)
           FROM submissions s
           JOIN company_reviews cr ON cr.submission_id = s.submission_id
          WHERE s.company_id = c.company_id
            AND s.submission_status = 'APPROVED')                       AS average_rating,
        (SELECT COUNT(*)::INTEGER
           FROM submissions s
           JOIN salary_submissions ss ON ss.submission_id = s.submission_id
          WHERE s.company_id = c.company_id
            AND s.submission_status = 'APPROVED')                       AS approved_salary_count,
        (SELECT MIN(ss.base_salary)::NUMERIC(12, 2)
           FROM submissions s
           JOIN salary_submissions ss ON ss.submission_id = s.submission_id
          WHERE s.company_id = c.company_id
            AND s.submission_status = 'APPROVED')                       AS minimum_salary,
        (SELECT MAX(ss.base_salary)::NUMERIC(12, 2)
           FROM submissions s
           JOIN salary_submissions ss ON ss.submission_id = s.submission_id
          WHERE s.company_id = c.company_id
            AND s.submission_status = 'APPROVED')                       AS maximum_salary,
        (SELECT ROUND(AVG(ss.base_salary), 2)::NUMERIC(12, 2)
           FROM submissions s
           JOIN salary_submissions ss ON ss.submission_id = s.submission_id
          WHERE s.company_id = c.company_id
            AND s.submission_status = 'APPROVED')                       AS average_salary,
        (SELECT COUNT(*)::INTEGER
           FROM submissions s
           JOIN interview_experiences ie ON ie.submission_id = s.submission_id
          WHERE s.company_id = c.company_id
            AND s.submission_status = 'APPROVED')                       AS interview_count,
        (SELECT COUNT(*)::INTEGER
           FROM job_postings jp
          WHERE jp.company_id = c.company_id
            AND jp.job_status = 'PUBLISHED'
            AND jp.application_deadline >= CURRENT_DATE)                AS open_job_count
    FROM companies c
    WHERE c.company_id = p_company_id;
$$;

COMMENT ON FUNCTION saple_company_insight_summary(BIGINT) IS
    'Approved-only public statistics for one company: reviews, rating, salary spread, interviews and open jobs.';

-- ---------------------------------------------------------------------------
-- 3. Procedure: one application decision, two tables
--
-- A decision must change job_applications and record job_application_status_history
-- together, or not at all. The procedure locks the application row, checks the
-- transition against the list of statuses the caller's role is allowed to move
-- from, writes both tables, and returns what the caller needs for the
-- notification it sends in the same transaction.
--
-- It deliberately contains no COMMIT: the backend opens the transaction, calls
-- this procedure and inserts the applicant's notification, so all three writes
-- commit or roll back as one.
--
-- Errors use custom SQLSTATEs the repository maps to its existing API errors:
--   SA001 - application not found
--   SA002 - transition not allowed from the current status
--
-- Evaluation (disposable data only):
--   CALL saple_apply_application_decision(<application_id>, <actor_user_id>,
--        'UNDER_REVIEW', 'demo note', ARRAY['SUBMITTED']::VARCHAR[], TRUE,
--        NULL, NULL, NULL, NULL);
-- ---------------------------------------------------------------------------

DROP PROCEDURE IF EXISTS saple_apply_application_decision(
    BIGINT, BIGINT, VARCHAR, TEXT, VARCHAR[], BOOLEAN, VARCHAR, BIGINT, BIGINT, VARCHAR
);
CREATE PROCEDURE saple_apply_application_decision(
    IN    p_application_id       BIGINT,
    IN    p_actor_user_id        BIGINT,
    IN    p_new_status           VARCHAR,
    IN    p_note                 TEXT,
    IN    p_allowed_previous     VARCHAR[],
    IN    p_is_reviewer_decision BOOLEAN,
    INOUT io_previous_status     VARCHAR,
    INOUT io_history_id          BIGINT,
    INOUT io_applicant_user_id   BIGINT,
    INOUT io_job_title           VARCHAR
)
LANGUAGE plpgsql
AS $$
DECLARE
    v_application RECORD;
BEGIN
    -- FOR UPDATE: two reviewers deciding at once queue here instead of
    -- overwriting one another's decision.
    SELECT ja.application_id,
           ja.applicant_user_id,
           ja.application_status,
           jp.title
      INTO v_application
      FROM job_applications ja
      JOIN job_postings jp ON jp.job_id = ja.job_id
     WHERE ja.application_id = p_application_id
     FOR UPDATE OF ja;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Application not found'
            USING ERRCODE = 'SA001';
    END IF;

    IF NOT (v_application.application_status = ANY (p_allowed_previous)) THEN
        RAISE EXCEPTION 'Application cannot make that transition'
            USING ERRCODE = 'SA002';
    END IF;

    UPDATE job_applications
       SET application_status = p_new_status,
           reviewed_by = CASE WHEN p_is_reviewer_decision THEN p_actor_user_id ELSE NULL END,
           reviewed_at = CASE WHEN p_is_reviewer_decision THEN CURRENT_TIMESTAMP ELSE NULL END,
           updated_at = CURRENT_TIMESTAMP
     WHERE application_id = p_application_id;

    INSERT INTO job_application_status_history (
        application_id, actor_user_id, previous_status, new_status, action_note
    ) VALUES (
        p_application_id, p_actor_user_id, v_application.application_status, p_new_status, p_note
    )
    RETURNING history_id INTO io_history_id;

    io_previous_status   := v_application.application_status;
    io_applicant_user_id := v_application.applicant_user_id;
    io_job_title         := v_application.title;
END;
$$;

COMMENT ON PROCEDURE saple_apply_application_decision(
    BIGINT, BIGINT, VARCHAR, TEXT, VARCHAR[], BOOLEAN, VARCHAR, BIGINT, BIGINT, VARCHAR
) IS
    'Applies one job-application decision: locks the row, validates the transition, updates job_applications and writes job_application_status_history.';


-- 12. ML-ASSISTED MODERATION (additive migration 011)
-- ML-assisted moderation. Human decisions remain final. Existing submissions
-- and public views stay unchanged until the application enables screening.
-- Run only after 010_job_application_resumes.sql; never apply automatically.
CREATE TABLE ml_model_registry (
    model_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    model_key VARCHAR(160) NOT NULL,
    content_type VARCHAR(16) NOT NULL,
    scope_key VARCHAR(160),
    model_version VARCHAR(80) NOT NULL,
    artifact_uri TEXT NOT NULL,
    artifact_sha256 CHAR(64) NOT NULL,
    feature_schema_version VARCHAR(80) NOT NULL,
    training_dataset_fingerprint CHAR(64) NOT NULL,
    trained_at TIMESTAMPTZ NOT NULL,
    training_sample_count INTEGER NOT NULL,
    approved_sample_count INTEGER NOT NULL,
    rejected_sample_count INTEGER NOT NULL,
    metrics JSONB NOT NULL DEFAULT '{}'::jsonb,
    auto_publish_threshold NUMERIC(6,5),
    ood_threshold NUMERIC,
    status VARCHAR(12) NOT NULL DEFAULT 'CANDIDATE',
    activated_at TIMESTAMPTZ,
    retired_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_ml_model_registry PRIMARY KEY (model_id),
    CONSTRAINT uq_ml_model_registry_version UNIQUE (model_key, model_version),
    CONSTRAINT ck_ml_model_registry_type CHECK (content_type IN ('SALARY','REVIEW','INTERVIEW','JOB','PROFILE','COMPANY')),
    CONSTRAINT ck_ml_model_registry_status CHECK (status IN ('CANDIDATE','ACTIVE','RETIRED','DISABLED')),
    CONSTRAINT ck_ml_model_registry_sha CHECK (artifact_sha256 ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_ml_model_registry_fingerprint CHECK (training_dataset_fingerprint ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_ml_model_registry_counts CHECK (training_sample_count >= 0 AND approved_sample_count >= 0 AND rejected_sample_count >= 0),
    CONSTRAINT ck_ml_model_registry_threshold CHECK (auto_publish_threshold IS NULL OR auto_publish_threshold BETWEEN 0 AND 1)
);
CREATE UNIQUE INDEX uq_ml_model_registry_active
    ON ml_model_registry (model_key) WHERE status = 'ACTIVE';

CREATE TABLE content_screenings (
    screening_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    entity_type VARCHAR(16) NOT NULL,
    entity_id BIGINT NOT NULL,
    revision_no INTEGER NOT NULL DEFAULT 1,
    submitted_by_user_id BIGINT,
    model_key VARCHAR(160),
    model_version VARCHAR(80),
    feature_schema_version VARCHAR(80),
    screening_status VARCHAR(16) NOT NULL,
    risk_probability NUMERIC(6,5),
    safe_probability NUMERIC(6,5),
    confidence NUMERIC(6,5),
    reason_codes JSONB NOT NULL DEFAULT '[]'::jsonb,
    model_metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    publication_state VARCHAR(12) NOT NULL DEFAULT 'HELD',
    manual_review_status VARCHAR(10) NOT NULL DEFAULT 'PENDING',
    screened_at TIMESTAMPTZ,
    provisional_published_at TIMESTAMPTZ,
    human_review_due_at TIMESTAMPTZ,
    reviewed_at TIMESTAMPTZ,
    reviewed_by BIGINT,
    human_decision_note TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_content_screenings PRIMARY KEY (screening_id),
    CONSTRAINT uq_content_screenings_revision UNIQUE (entity_type, entity_id, revision_no),
    CONSTRAINT fk_content_screenings_submitter FOREIGN KEY (submitted_by_user_id) REFERENCES users (user_id),
    CONSTRAINT fk_content_screenings_reviewer FOREIGN KEY (reviewed_by) REFERENCES users (user_id),
    CONSTRAINT ck_content_screenings_type CHECK (entity_type IN ('SALARY','REVIEW','INTERVIEW','JOB','PROFILE','COMPANY')),
    CONSTRAINT ck_content_screenings_status CHECK (screening_status IN ('NOT_RUN','AUTO_PUBLISH','MANUAL_REVIEW','UNAVAILABLE','ERROR')),
    CONSTRAINT ck_content_screenings_publication CHECK (publication_state IN ('HELD','PROVISIONAL','CONFIRMED','REMOVED')),
    CONSTRAINT ck_content_screenings_manual CHECK (manual_review_status IN ('PENDING','APPROVED','REJECTED')),
    CONSTRAINT ck_content_screenings_revision CHECK (revision_no > 0),
    CONSTRAINT ck_content_screenings_risk CHECK (risk_probability IS NULL OR risk_probability BETWEEN 0 AND 1),
    CONSTRAINT ck_content_screenings_safe CHECK (safe_probability IS NULL OR safe_probability BETWEEN 0 AND 1),
    CONSTRAINT ck_content_screenings_confidence CHECK (confidence IS NULL OR confidence BETWEEN 0 AND 1),
    CONSTRAINT ck_content_screenings_reasons CHECK (jsonb_typeof(reason_codes) = 'array'),
    CONSTRAINT ck_content_screenings_metadata CHECK (jsonb_typeof(model_metadata) = 'object'),
    CONSTRAINT ck_content_screenings_provisional CHECK (publication_state <> 'PROVISIONAL' OR (screening_status = 'AUTO_PUBLISH' AND provisional_published_at IS NOT NULL))
);
CREATE INDEX ix_content_screenings_queue
    ON content_screenings (manual_review_status, publication_state, created_at);
CREATE INDEX ix_content_screenings_entity
    ON content_screenings (entity_type, entity_id, revision_no DESC);

CREATE TABLE professional_profile_revisions (
    revision_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    revision_no INTEGER NOT NULL,
    previous_public_snapshot JSONB NOT NULL,
    proposed_public_snapshot JSONB NOT NULL,
    applied_at TIMESTAMPTZ,
    screening_id BIGINT,
    review_status VARCHAR(10) NOT NULL DEFAULT 'PENDING',
    reviewed_at TIMESTAMPTZ,
    reviewed_by BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_professional_profile_revisions PRIMARY KEY (revision_id),
    CONSTRAINT uq_professional_profile_revisions_user_no UNIQUE (user_id, revision_no),
    CONSTRAINT fk_professional_profile_revisions_user FOREIGN KEY (user_id) REFERENCES users (user_id),
    CONSTRAINT fk_professional_profile_revisions_screening FOREIGN KEY (screening_id) REFERENCES content_screenings (screening_id),
    CONSTRAINT fk_professional_profile_revisions_reviewer FOREIGN KEY (reviewed_by) REFERENCES users (user_id),
    CONSTRAINT ck_professional_profile_revisions_review CHECK (review_status IN ('PENDING','APPROVED','REJECTED')),
    CONSTRAINT ck_professional_profile_revisions_previous CHECK (jsonb_typeof(previous_public_snapshot) = 'object'),
    CONSTRAINT ck_professional_profile_revisions_proposed CHECK (jsonb_typeof(proposed_public_snapshot) = 'object')
);

-- Central public visibility rule: a final human approval, or the latest
-- pending screening explicitly marked provisional. Existing rows remain
-- visible exactly as before; verified salary and rating aggregates still use
-- final APPROVED rows only.
CREATE OR REPLACE VIEW vw_public_visible_submissions AS
SELECT s.*,
       (s.submission_status = 'PENDING') AS awaiting_moderator_review
FROM submissions s
WHERE s.submission_status = 'APPROVED'
   OR (s.submission_status = 'PENDING' AND EXISTS (
       SELECT 1 FROM content_screenings cs
       WHERE cs.entity_type = s.submission_type AND cs.entity_id = s.submission_id
         AND cs.publication_state = 'PROVISIONAL'
         AND cs.revision_no = (SELECT MAX(latest.revision_no) FROM content_screenings latest
             WHERE latest.entity_type = cs.entity_type AND latest.entity_id = cs.entity_id)
   ));

-- Only final human labels from non-synthetic accounts are training inputs.
CREATE OR REPLACE VIEW vw_ml_human_reviewed_real_submissions AS
SELECT s.submission_id, s.user_id, s.company_id, s.submission_type,
       s.submission_status, s.verification_status, s.submitted_at, s.updated_at
FROM submissions s JOIN users u ON u.user_id = s.user_id
WHERE s.submission_status IN ('APPROVED','REJECTED')
  AND u.password_hash NOT LIKE '%SAPLE.BULK.DEMO.ACCOUNT.NO.LOGIN%'
  AND u.password_hash NOT LIKE '%DEMO_HASH_NOT_FOR_PRODUCTION%'
  AND u.email NOT LIKE '%@example.invalid'
  AND u.email NOT LIKE '%@example.test';

COMMIT;
