-- SAPLE SUPABASE POSTGRESQL SCHEMA
-- PostgreSQL equivalent of database/sql/01_final_schema.sql.
-- The Oracle files remain the preserved prior milestone implementation.

BEGIN;

-- ================================================================
-- 1. ACCOUNTS AND IDENTITY
-- ================================================================

-- USERS stores login identity, account state and authorization.
-- ACCOUNT_ROLE is independent from USER_TYPE.
CREATE TABLE users (
    user_id        BIGINT GENERATED BY DEFAULT AS IDENTITY,
    full_name      VARCHAR(120) NOT NULL,
    email          VARCHAR(254) NOT NULL,
    password_hash  VARCHAR(255) NOT NULL,
    user_type      VARCHAR(10) DEFAULT 'NORMAL' NOT NULL,
    account_role   VARCHAR(25) DEFAULT 'USER' NOT NULL,
    account_status VARCHAR(15) DEFAULT 'ACTIVE' NOT NULL,
    token_version  INTEGER DEFAULT 0 NOT NULL,
    created_at     TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL, --more precision than DATE
    updated_at     TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (user_id),
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT ck_users_full_name CHECK (TRIM(full_name) <> ''),
    CONSTRAINT ck_users_email CHECK (TRIM(email) <> ''),
    CONSTRAINT ck_users_password_hash CHECK (LENGTH(password_hash) >= 20),
    CONSTRAINT ck_users_type CHECK (user_type IN ('NORMAL', 'EMPLOYEE')),
    CONSTRAINT ck_users_role CHECK (account_role IN ('USER', 'ADMIN', 'COMPANY_REPRESENTATIVE')),
    CONSTRAINT ck_users_status CHECK (account_status IN ('ACTIVE', 'SUSPENDED', 'DEACTIVATED')),
    CONSTRAINT ck_users_token_version CHECK (token_version >= 0)
);

-- EMPLOYEES is the optional one-to-one employment profile for a user.
CREATE TABLE employees (
    employee_id       BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id           BIGINT NOT NULL,
    employment_status VARCHAR(10) NOT NULL,
    created_at        TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_employees PRIMARY KEY (employee_id),
    CONSTRAINT uk_employees_user UNIQUE (user_id),
    CONSTRAINT fk_employees_user FOREIGN KEY (user_id)
        REFERENCES users (user_id) ON DELETE CASCADE,
    CONSTRAINT ck_employees_status CHECK (employment_status IN ('CURRENT', 'FORMER'))
);

-- PASSWORD_RESET_TOKENS stores only single-use, expiring token hashes.
CREATE TABLE password_reset_tokens (
    reset_token_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id        BIGINT NOT NULL,
    token_hash     VARCHAR(64) NOT NULL,
    expires_at     TIMESTAMPTZ NOT NULL,
    used_at        TIMESTAMPTZ,
    revoked_at     TIMESTAMPTZ,
    created_at     TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_password_reset_tokens PRIMARY KEY (reset_token_id),
    CONSTRAINT uk_password_reset_token_hash UNIQUE (token_hash),
    CONSTRAINT fk_password_reset_user FOREIGN KEY (user_id)
        REFERENCES users (user_id) ON DELETE CASCADE,
    CONSTRAINT ck_password_reset_token_hash CHECK (LENGTH(token_hash) = 64),
    CONSTRAINT ck_password_reset_expiry CHECK (expires_at > created_at),
    CONSTRAINT ck_password_reset_state CHECK (used_at IS NULL OR revoked_at IS NULL)
);

-- ================================================================
-- 2. COMPANY REFERENCE DATA
-- ================================================================

-- COMPANIES stores the public reference profile for each company.
CREATE TABLE companies (
    company_id        BIGINT GENERATED BY DEFAULT AS IDENTITY,
    company_name      VARCHAR(150) NOT NULL,
    industry          VARCHAR(100) NOT NULL,
    headquarters_city VARCHAR(100) NOT NULL,
    country           VARCHAR(100) NOT NULL,
    website           VARCHAR(255),
    company_size      VARCHAR(30),
    description       TEXT, --character large object
    created_at        TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at        TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_companies PRIMARY KEY (company_id),
    CONSTRAINT uk_companies_name UNIQUE (company_name),
    CONSTRAINT ck_companies_name CHECK (TRIM(company_name) <> ''),
    CONSTRAINT ck_companies_industry CHECK (TRIM(industry) <> ''),
    CONSTRAINT ck_companies_city CHECK (TRIM(headquarters_city) <> ''),
    CONSTRAINT ck_companies_country CHECK (TRIM(country) <> '')
);

-- JOB_ROLES is the reusable catalog of job designations.
CREATE TABLE job_roles (
    role_id       BIGINT GENERATED BY DEFAULT AS IDENTITY,
    role_name     VARCHAR(120) NOT NULL,
    role_category VARCHAR(100),
    description   VARCHAR(500),
    CONSTRAINT pk_job_roles PRIMARY KEY (role_id),
    CONSTRAINT uk_job_roles_name UNIQUE (role_name),
    CONSTRAINT ck_job_roles_name CHECK (TRIM(role_name) <> '')
);

-- BENEFITS is the reusable catalog of employee benefits.
CREATE TABLE benefits (
    benefit_id       BIGINT GENERATED BY DEFAULT AS IDENTITY,
    benefit_name     VARCHAR(120) NOT NULL,
    benefit_category VARCHAR(100),
    description      VARCHAR(500),
    CONSTRAINT pk_benefits PRIMARY KEY (benefit_id),
    CONSTRAINT uk_benefits_name UNIQUE (benefit_name),
    CONSTRAINT ck_benefits_name CHECK (TRIM(benefit_name) <> '')
);

-- COMPANY_BENEFITS resolves the company-benefit many-to-many relationship.
CREATE TABLE company_benefits (
    company_id  BIGINT NOT NULL,
    benefit_id  BIGINT NOT NULL,
    details     VARCHAR(500),
    eligibility VARCHAR(250),
    last_updated TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_company_benefits PRIMARY KEY (company_id, benefit_id),
    CONSTRAINT fk_company_benefits_company FOREIGN KEY (company_id)
        REFERENCES companies (company_id) ON DELETE CASCADE,
    CONSTRAINT fk_company_benefits_benefit FOREIGN KEY (benefit_id)
        REFERENCES benefits (benefit_id) ON DELETE CASCADE
);

-- ================================================================
-- 3. EMPLOYMENT VERIFICATION
-- ================================================================

-- EMPLOYMENT_VERIFICATIONS scopes employee trust to a company and job role.
-- ROLE_ID remains nullable only for migration-07 legacy compatibility.
CREATE TABLE employment_verifications (
    verification_id     BIGINT GENERATED BY DEFAULT AS IDENTITY,
    employee_id         BIGINT NOT NULL,
    company_id          BIGINT NOT NULL,
    role_id             BIGINT,
    verification_method VARCHAR(30) NOT NULL,
    company_email       VARCHAR(254),
    proof_type          VARCHAR(30),
    proof_reference     VARCHAR(255),
    verification_status VARCHAR(10) DEFAULT 'PENDING' NOT NULL,
    requested_at        TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    reviewed_at         TIMESTAMPTZ,
    expires_at          TIMESTAMPTZ,
    rejection_reason    VARCHAR(500),
    reviewed_by         BIGINT,
    CONSTRAINT pk_employment_verifications PRIMARY KEY (verification_id),
    CONSTRAINT fk_emp_verify_employee FOREIGN KEY (employee_id)
        REFERENCES employees (employee_id) ON DELETE CASCADE,
    CONSTRAINT fk_emp_verify_company FOREIGN KEY (company_id)
        REFERENCES companies (company_id) ON DELETE CASCADE,
    CONSTRAINT fk_emp_verify_role FOREIGN KEY (role_id)
        REFERENCES job_roles (role_id),
    CONSTRAINT fk_emp_verify_reviewer FOREIGN KEY (reviewed_by)
        REFERENCES users (user_id),
    CONSTRAINT ck_emp_verify_method CHECK (verification_method IN ('COMPANY_EMAIL_OTP', 'DOCUMENT')),
    CONSTRAINT ck_emp_verify_status CHECK (verification_status IN ('VERIFIED', 'PENDING', 'REJECTED', 'EXPIRED')),
    CONSTRAINT ck_emp_verify_proof CHECK (
        (verification_method = 'COMPANY_EMAIL_OTP' AND company_email IS NOT NULL AND proof_reference IS NULL)
        OR
        (verification_method = 'DOCUMENT' AND proof_type IS NOT NULL AND proof_reference IS NOT NULL AND company_email IS NULL)
    ),
    CONSTRAINT ck_emp_verify_review CHECK (
        (verification_status = 'PENDING' AND reviewed_at IS NULL AND reviewed_by IS NULL)
        OR
        (verification_status <> 'PENDING' AND reviewed_at IS NOT NULL AND reviewed_by IS NOT NULL)
    ),
    CONSTRAINT ck_emp_verify_rejection CHECK (
        verification_status = 'REJECTED' OR rejection_reason IS NULL
    )
);

-- ================================================================
-- 4. SUBMISSION PARENT TABLE
-- ================================================================

-- SUBMISSIONS stores shared ownership, anonymity and workflow state.
CREATE TABLE submissions (
    submission_id       BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id             BIGINT NOT NULL,
    company_id          BIGINT NOT NULL,
    submission_type     VARCHAR(10) NOT NULL,
    is_anonymous        INTEGER DEFAULT 1 NOT NULL,
    submission_status   VARCHAR(10) DEFAULT 'PENDING' NOT NULL,
    verification_status VARCHAR(10) DEFAULT 'UNVERIFIED' NOT NULL,
    submitted_at        TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    approved_at         TIMESTAMPTZ,
    updated_at          TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_submissions PRIMARY KEY (submission_id),
    CONSTRAINT fk_submissions_user FOREIGN KEY (user_id)
        REFERENCES users (user_id),
    CONSTRAINT fk_submissions_company FOREIGN KEY (company_id)
        REFERENCES companies (company_id),
    CONSTRAINT ck_submissions_type CHECK (submission_type IN ('SALARY', 'REVIEW', 'INTERVIEW')),
    CONSTRAINT ck_submissions_anonymous CHECK (is_anonymous IN (0, 1)),
    CONSTRAINT ck_submissions_status CHECK (submission_status IN ('PENDING', 'APPROVED', 'FLAGGED', 'REJECTED')),
    CONSTRAINT ck_submissions_verify CHECK (verification_status IN ('VERIFIED', 'UNVERIFIED', 'PENDING', 'REJECTED')),
    CONSTRAINT ck_submissions_approved_at CHECK (
        (submission_status = 'APPROVED' AND approved_at IS NOT NULL)
        OR
        (submission_status <> 'APPROVED' AND approved_at IS NULL)
    )
);

-- ================================================================
-- 5. SUBMISSION SUBTYPE TABLES
-- ================================================================

-- SALARY_SUBMISSIONS extends one parent submission with salary details.
CREATE TABLE salary_submissions (
    submission_id           BIGINT,
    role_id                 BIGINT NOT NULL,
    base_salary             NUMERIC(12,2) NOT NULL,
    additional_compensation NUMERIC(12,2),
    currency                VARCHAR(3) DEFAULT 'BDT' NOT NULL,
    pay_period              VARCHAR(10) NOT NULL,
    years_of_experience     NUMERIC(4,1) NOT NULL,
    employment_type         VARCHAR(15) NOT NULL,
    work_mode               VARCHAR(10) NOT NULL,
    salary_year             INTEGER NOT NULL,
    CONSTRAINT pk_salary_submissions PRIMARY KEY (submission_id),
    CONSTRAINT fk_salary_submission FOREIGN KEY (submission_id)
        REFERENCES submissions (submission_id) ON DELETE CASCADE,
    CONSTRAINT fk_salary_role FOREIGN KEY (role_id)
        REFERENCES job_roles (role_id),
    CONSTRAINT ck_salary_base CHECK (base_salary > 0 AND base_salary <= 9999999999.99),
    CONSTRAINT ck_salary_additional CHECK (additional_compensation IS NULL OR additional_compensation >= 0),
    CONSTRAINT ck_salary_currency CHECK (LENGTH(currency) = 3 AND currency = UPPER(currency)),
    CONSTRAINT ck_salary_period CHECK (pay_period IN ('MONTHLY', 'YEARLY')),
    CONSTRAINT ck_salary_experience CHECK (years_of_experience BETWEEN 0 AND 60),
    CONSTRAINT ck_salary_employment CHECK (employment_type IN ('FULL_TIME', 'PART_TIME', 'CONTRACT', 'INTERN')),
    CONSTRAINT ck_salary_work_mode CHECK (work_mode IN ('ONSITE', 'HYBRID', 'REMOTE')),
    CONSTRAINT ck_salary_year CHECK (salary_year BETWEEN 2000 AND 2100)
);

-- COMPANY_REVIEWS extends one parent submission with workplace feedback.
CREATE TABLE company_reviews (
    submission_id            BIGINT,
    role_id                  BIGINT,
    review_title             VARCHAR(200) NOT NULL,
    overall_rating           NUMERIC(2,1) NOT NULL,
    work_life_balance_rating NUMERIC(2,1) NOT NULL,
    career_growth_rating     NUMERIC(2,1) NOT NULL,
    management_rating        NUMERIC(2,1) NOT NULL,
    culture_rating           NUMERIC(2,1) NOT NULL,
    pros                     TEXT NOT NULL,
    cons                     TEXT NOT NULL,
    advice_to_management     TEXT,
    employment_status        VARCHAR(10) NOT NULL,
    review_date              DATE NOT NULL,
    CONSTRAINT pk_company_reviews PRIMARY KEY (submission_id),
    CONSTRAINT fk_review_submission FOREIGN KEY (submission_id)
        REFERENCES submissions (submission_id) ON DELETE CASCADE,
    CONSTRAINT fk_review_role FOREIGN KEY (role_id)
        REFERENCES job_roles (role_id),
    CONSTRAINT ck_review_title CHECK (TRIM(review_title) <> ''),
    CONSTRAINT ck_review_overall CHECK (overall_rating BETWEEN 1 AND 5),
    CONSTRAINT ck_review_work_life CHECK (work_life_balance_rating BETWEEN 1 AND 5),
    CONSTRAINT ck_review_growth CHECK (career_growth_rating BETWEEN 1 AND 5),
    CONSTRAINT ck_review_management CHECK (management_rating BETWEEN 1 AND 5),
    CONSTRAINT ck_review_culture CHECK (culture_rating BETWEEN 1 AND 5),
    CONSTRAINT ck_review_pros CHECK (LENGTH(pros) > 0),
    CONSTRAINT ck_review_cons CHECK (LENGTH(cons) > 0),
    CONSTRAINT ck_review_employment CHECK (employment_status IN ('CURRENT', 'FORMER'))
);

-- INTERVIEW_EXPERIENCES extends one parent submission with interview details.
CREATE TABLE interview_experiences (
    submission_id       BIGINT,
    role_id             BIGINT NOT NULL,
    interview_date      DATE NOT NULL,
    difficulty_level    VARCHAR(10) NOT NULL,
    rounds_count        INTEGER NOT NULL,
    interview_mode      VARCHAR(10) NOT NULL,
    result_status       VARCHAR(10) NOT NULL,
    duration_days       INTEGER NOT NULL,
    process_description TEXT NOT NULL,
    questions_summary   TEXT,
    CONSTRAINT pk_interview_experiences PRIMARY KEY (submission_id),
    CONSTRAINT fk_interview_submission FOREIGN KEY (submission_id)
        REFERENCES submissions (submission_id) ON DELETE CASCADE,
    CONSTRAINT fk_interview_role FOREIGN KEY (role_id)
        REFERENCES job_roles (role_id),
    CONSTRAINT ck_interview_difficulty CHECK (difficulty_level IN ('EASY', 'MEDIUM', 'HARD')),
    CONSTRAINT ck_interview_rounds CHECK (rounds_count BETWEEN 1 AND 20),
    CONSTRAINT ck_interview_mode CHECK (interview_mode IN ('ONLINE', 'ONSITE', 'HYBRID')),
    CONSTRAINT ck_interview_result CHECK (result_status IN ('OFFERED', 'REJECTED', 'PENDING', 'WITHDREW')),
    CONSTRAINT ck_interview_duration CHECK (duration_days BETWEEN 0 AND 365),
    CONSTRAINT ck_interview_process CHECK (LENGTH(process_description) > 0)
);

-- ================================================================
-- 6. REPORTING AND MODERATION
-- ================================================================

-- REPORTS stores user complaints and their resolution workflow.
CREATE TABLE reports (
    report_id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    reporter_user_id   BIGINT NOT NULL,
    submission_id      BIGINT NOT NULL,
    reason_category    VARCHAR(15) NOT NULL,
    report_description VARCHAR(1000),
    report_status      VARCHAR(10) DEFAULT 'OPEN' NOT NULL,
    reported_at        TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    resolved_at        TIMESTAMPTZ,
    resolution_note    VARCHAR(1000),
    resolved_by        BIGINT,
    CONSTRAINT pk_reports PRIMARY KEY (report_id),
    CONSTRAINT uk_reports_reporter_submission UNIQUE (reporter_user_id, submission_id),
    CONSTRAINT fk_reports_reporter FOREIGN KEY (reporter_user_id)
        REFERENCES users (user_id),
    CONSTRAINT fk_reports_submission FOREIGN KEY (submission_id)
        REFERENCES submissions (submission_id) ON DELETE CASCADE,
    CONSTRAINT fk_reports_resolver FOREIGN KEY (resolved_by)
        REFERENCES users (user_id),
    CONSTRAINT ck_reports_reason CHECK (reason_category IN ('FAKE_DATA', 'DEFAMATION', 'SPAM', 'PRIVACY', 'OTHER')),
    CONSTRAINT ck_reports_status CHECK (report_status IN ('OPEN', 'REVIEWING', 'RESOLVED', 'DISMISSED')),
    CONSTRAINT ck_reports_resolution CHECK (
        (report_status IN ('OPEN', 'REVIEWING') AND resolved_at IS NULL AND resolved_by IS NULL)
        OR
        (report_status IN ('RESOLVED', 'DISMISSED') AND resolved_at IS NOT NULL AND resolved_by IS NOT NULL)
    )
);

-- MODERATION_ACTIONS stores append-only submission moderation history.
CREATE TABLE moderation_actions (
    action_id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    submission_id     BIGINT NOT NULL,
    moderator_user_id BIGINT NOT NULL,
    action_type       VARCHAR(15) NOT NULL,
    previous_status   VARCHAR(10),
    new_status        VARCHAR(10) NOT NULL,
    action_note       VARCHAR(1000),
    action_at         TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_moderation_actions PRIMARY KEY (action_id),
    CONSTRAINT fk_mod_actions_submission FOREIGN KEY (submission_id)
        REFERENCES submissions (submission_id) ON DELETE CASCADE,
    CONSTRAINT fk_mod_actions_moderator FOREIGN KEY (moderator_user_id)
        REFERENCES users (user_id),
    CONSTRAINT ck_mod_actions_type CHECK (action_type IN ('APPROVE', 'REJECT', 'FLAG', 'UNFLAG', 'EDIT_STATUS')),
    CONSTRAINT ck_mod_actions_previous CHECK (previous_status IS NULL OR previous_status IN ('PENDING', 'APPROVED', 'FLAGGED', 'REJECTED')),
    CONSTRAINT ck_mod_actions_new CHECK (new_status IN ('PENDING', 'APPROVED', 'FLAGGED', 'REJECTED'))
);

-- ================================================================
-- 7. COMPANY REPRESENTATIVES
-- ================================================================

-- COMPANY_REPRESENTATIVES binds one account to one company with an
-- administrator-controlled lifecycle. Public registration can never write here.
CREATE TABLE company_representatives (
    assignment_id     BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id           BIGINT NOT NULL,
    company_id        BIGINT NOT NULL,
    job_title         VARCHAR(120),
    assignment_status VARCHAR(10) DEFAULT 'PENDING' NOT NULL,
    request_note      VARCHAR(1000),
    decision_note     VARCHAR(1000),
    approved_by       BIGINT,
    approved_at       TIMESTAMPTZ,
    revoked_by        BIGINT,
    revoked_at        TIMESTAMPTZ,
    created_at        TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at        TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_company_representatives PRIMARY KEY (assignment_id),
    CONSTRAINT fk_company_rep_user FOREIGN KEY (user_id)
        REFERENCES users (user_id) ON DELETE CASCADE,
    CONSTRAINT fk_company_rep_company FOREIGN KEY (company_id)
        REFERENCES companies (company_id) ON DELETE RESTRICT,
    CONSTRAINT fk_company_rep_approver FOREIGN KEY (approved_by)
        REFERENCES users (user_id),
    CONSTRAINT fk_company_rep_revoker FOREIGN KEY (revoked_by)
        REFERENCES users (user_id),
    CONSTRAINT ck_company_rep_status
        CHECK (assignment_status IN ('PENDING', 'ACTIVE', 'REJECTED', 'REVOKED')),
    CONSTRAINT ck_company_rep_job_title
        CHECK (job_title IS NULL OR TRIM(job_title) <> ''),
    CONSTRAINT ck_company_rep_approval CHECK (
        (assignment_status = 'PENDING' AND approved_by IS NULL AND approved_at IS NULL)
        OR
        (assignment_status IN ('ACTIVE', 'REVOKED') AND approved_by IS NOT NULL AND approved_at IS NOT NULL)
        OR
        (assignment_status = 'REJECTED' AND approved_by IS NULL AND approved_at IS NULL)
    ),
    CONSTRAINT ck_company_rep_revocation CHECK (
        (assignment_status = 'REVOKED' AND revoked_by IS NOT NULL AND revoked_at IS NOT NULL)
        OR
        (assignment_status <> 'REVOKED' AND revoked_by IS NULL AND revoked_at IS NULL)
    ),
    CONSTRAINT ck_company_rep_decision_note CHECK (
        assignment_status NOT IN ('REJECTED', 'REVOKED') OR decision_note IS NOT NULL
    )
);

-- REPRESENTATIVE_ASSIGNMENT_ACTIONS stores append-only assignment history.
CREATE TABLE representative_assignment_actions (
    action_id       BIGINT GENERATED BY DEFAULT AS IDENTITY,
    assignment_id   BIGINT NOT NULL,
    actor_user_id   BIGINT NOT NULL,
    action_type     VARCHAR(10) NOT NULL,
    previous_status VARCHAR(10),
    new_status      VARCHAR(10) NOT NULL,
    action_note     VARCHAR(1000),
    action_at       TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_representative_assignment_actions PRIMARY KEY (action_id),
    CONSTRAINT fk_rep_action_assignment FOREIGN KEY (assignment_id)
        REFERENCES company_representatives (assignment_id) ON DELETE RESTRICT,
    CONSTRAINT fk_rep_action_actor FOREIGN KEY (actor_user_id)
        REFERENCES users (user_id),
    CONSTRAINT ck_rep_action_type
        CHECK (action_type IN ('REQUEST', 'APPROVE', 'REJECT', 'REVOKE')),
    CONSTRAINT ck_rep_action_previous
        CHECK (previous_status IS NULL OR previous_status IN ('PENDING', 'ACTIVE', 'REJECTED', 'REVOKED')),
    CONSTRAINT ck_rep_action_new
        CHECK (new_status IN ('PENDING', 'ACTIVE', 'REJECTED', 'REVOKED'))
);

-- ================================================================
-- 8. JOBS AND APPLICATIONS
-- ================================================================

-- JOB_POSTINGS is owned by one company and created inside a representative scope.
CREATE TABLE job_postings (
    job_id               BIGINT GENERATED BY DEFAULT AS IDENTITY,
    company_id           BIGINT NOT NULL,
    created_by_user_id   BIGINT NOT NULL,
    created_by_assignment_id BIGINT,
    role_id              BIGINT,
    title                VARCHAR(160) NOT NULL,
    description          TEXT NOT NULL,
    requirements         TEXT,
    location             VARCHAR(120) NOT NULL,
    employment_type      VARCHAR(15) NOT NULL,
    work_mode            VARCHAR(10) NOT NULL,
    salary_min           NUMERIC(12,2),
    salary_max           NUMERIC(12,2),
    salary_currency      VARCHAR(3),
    salary_period        VARCHAR(10),
    application_deadline DATE NOT NULL,
    job_status           VARCHAR(10) DEFAULT 'DRAFT' NOT NULL,
    published_at         TIMESTAMPTZ,
    closed_at            TIMESTAMPTZ,
    created_at           TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at           TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_job_postings PRIMARY KEY (job_id),
    CONSTRAINT fk_job_company FOREIGN KEY (company_id)
        REFERENCES companies (company_id) ON DELETE RESTRICT,
    CONSTRAINT fk_job_creator FOREIGN KEY (created_by_user_id)
        REFERENCES users (user_id),
    CONSTRAINT fk_job_assignment FOREIGN KEY (created_by_assignment_id)
        REFERENCES company_representatives (assignment_id) ON DELETE SET NULL,
    CONSTRAINT fk_job_role FOREIGN KEY (role_id)
        REFERENCES job_roles (role_id),
    CONSTRAINT ck_job_title CHECK (TRIM(title) <> ''),
    CONSTRAINT ck_job_description CHECK (LENGTH(TRIM(description)) >= 20),
    CONSTRAINT ck_job_location CHECK (TRIM(location) <> ''),
    CONSTRAINT ck_job_employment_type
        CHECK (employment_type IN ('FULL_TIME', 'PART_TIME', 'CONTRACT', 'INTERN')),
    CONSTRAINT ck_job_work_mode CHECK (work_mode IN ('ONSITE', 'HYBRID', 'REMOTE')),
    CONSTRAINT ck_job_status CHECK (job_status IN ('DRAFT', 'PUBLISHED', 'CLOSED', 'ARCHIVED')),
    CONSTRAINT ck_job_salary_range CHECK (
        (salary_min IS NULL AND salary_max IS NULL AND salary_currency IS NULL AND salary_period IS NULL)
        OR
        (salary_min IS NOT NULL AND salary_max IS NOT NULL
            AND salary_currency IS NOT NULL AND salary_period IS NOT NULL
            AND salary_min > 0 AND salary_max >= salary_min
            AND salary_max <= 9999999999.99)
    ),
    CONSTRAINT ck_job_salary_currency CHECK (
        salary_currency IS NULL
        OR (LENGTH(salary_currency) = 3 AND salary_currency = UPPER(salary_currency))
    ),
    CONSTRAINT ck_job_salary_period CHECK (
        salary_period IS NULL OR salary_period IN ('MONTHLY', 'YEARLY')
    ),
    CONSTRAINT ck_job_published_at CHECK (
        (job_status = 'DRAFT' AND published_at IS NULL)
        OR
        (job_status <> 'DRAFT' AND published_at IS NOT NULL)
    ),
    CONSTRAINT ck_job_closed_at CHECK (
        (job_status IN ('CLOSED', 'ARCHIVED') AND closed_at IS NOT NULL)
        OR
        (job_status IN ('DRAFT', 'PUBLISHED') AND closed_at IS NULL)
    )
);

-- JOB_APPLICATIONS allows exactly one application per account and job.
-- Saple stores no uploaded documents and never fetches applicant-supplied URLs.
CREATE TABLE job_applications (
    application_id     BIGINT GENERATED BY DEFAULT AS IDENTITY,
    job_id             BIGINT NOT NULL,
    applicant_user_id  BIGINT NOT NULL,
    cover_letter       TEXT NOT NULL,
    application_status VARCHAR(15) DEFAULT 'SUBMITTED' NOT NULL,
    submitted_at       TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at         TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    reviewed_by        BIGINT,
    reviewed_at        TIMESTAMPTZ,
    CONSTRAINT pk_job_applications PRIMARY KEY (application_id),
    CONSTRAINT uk_job_applications_once UNIQUE (job_id, applicant_user_id),
    CONSTRAINT fk_application_job FOREIGN KEY (job_id)
        REFERENCES job_postings (job_id) ON DELETE RESTRICT,
    CONSTRAINT fk_application_applicant FOREIGN KEY (applicant_user_id)
        REFERENCES users (user_id),
    CONSTRAINT fk_application_reviewer FOREIGN KEY (reviewed_by)
        REFERENCES users (user_id),
    CONSTRAINT ck_application_cover_letter
        CHECK (LENGTH(TRIM(cover_letter)) BETWEEN 30 AND 4000),
    CONSTRAINT ck_application_status CHECK (application_status IN (
        'SUBMITTED', 'UNDER_REVIEW', 'SHORTLISTED', 'REJECTED', 'WITHDRAWN', 'ACCEPTED'
    )),
    CONSTRAINT ck_application_review CHECK (
        (application_status IN ('SUBMITTED', 'WITHDRAWN') AND reviewed_by IS NULL AND reviewed_at IS NULL)
        OR
        (application_status IN ('UNDER_REVIEW', 'SHORTLISTED', 'REJECTED', 'ACCEPTED')
            AND reviewed_by IS NOT NULL AND reviewed_at IS NOT NULL)
    )
);

-- JOB_APPLICATION_STATUS_HISTORY stores append-only application decisions.
CREATE TABLE job_application_status_history (
    history_id      BIGINT GENERATED BY DEFAULT AS IDENTITY,
    application_id  BIGINT NOT NULL,
    actor_user_id   BIGINT NOT NULL,
    previous_status VARCHAR(15),
    new_status      VARCHAR(15) NOT NULL,
    action_note     VARCHAR(1000),
    action_at       TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_job_application_status_history PRIMARY KEY (history_id),
    CONSTRAINT fk_application_history_application FOREIGN KEY (application_id)
        REFERENCES job_applications (application_id) ON DELETE RESTRICT,
    CONSTRAINT fk_application_history_actor FOREIGN KEY (actor_user_id)
        REFERENCES users (user_id),
    CONSTRAINT ck_application_history_previous CHECK (
        previous_status IS NULL OR previous_status IN (
            'SUBMITTED', 'UNDER_REVIEW', 'SHORTLISTED', 'REJECTED', 'WITHDRAWN', 'ACCEPTED'
        )
    ),
    CONSTRAINT ck_application_history_new CHECK (new_status IN (
        'SUBMITTED', 'UNDER_REVIEW', 'SHORTLISTED', 'REJECTED', 'WITHDRAWN', 'ACCEPTED'
    ))
);

-- ================================================================
-- 9. ANNOUNCEMENTS AND PRIVATE NOTIFICATIONS
-- ================================================================

-- ANNOUNCEMENTS holds public, admin-managed, plain-text notices.
CREATE TABLE announcements (
    announcement_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    title           VARCHAR(160) NOT NULL,
    message         VARCHAR(600) NOT NULL,
    severity        VARCHAR(10) DEFAULT 'INFO' NOT NULL,
    is_dismissible  BOOLEAN DEFAULT TRUE NOT NULL,
    is_active       BOOLEAN DEFAULT TRUE NOT NULL,
    starts_at       TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ends_at         TIMESTAMPTZ,
    created_by      BIGINT NOT NULL,
    created_at      TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at      TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_announcements PRIMARY KEY (announcement_id),
    CONSTRAINT fk_announcements_author FOREIGN KEY (created_by)
        REFERENCES users (user_id),
    CONSTRAINT ck_announcements_title CHECK (TRIM(title) <> ''),
    CONSTRAINT ck_announcements_message CHECK (TRIM(message) <> ''),
    CONSTRAINT ck_announcements_severity CHECK (severity IN ('INFO', 'WARNING', 'CRITICAL')),
    CONSTRAINT ck_announcements_window CHECK (ends_at IS NULL OR ends_at > starts_at),
    CONSTRAINT ck_announcements_plain_text CHECK (
        title !~ '[<>]' AND message !~ '[<>]'
    )
);

-- NOTIFICATIONS is always private to exactly one account.
CREATE TABLE notifications (
    notification_id     BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id             BIGINT NOT NULL,
    notification_type   VARCHAR(30) NOT NULL,
    title               VARCHAR(160) NOT NULL,
    message             VARCHAR(600) NOT NULL,
    related_entity_type VARCHAR(30),
    related_entity_id   BIGINT,
    read_at             TIMESTAMPTZ,
    created_at          TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_notifications PRIMARY KEY (notification_id),
    CONSTRAINT fk_notifications_user FOREIGN KEY (user_id)
        REFERENCES users (user_id) ON DELETE CASCADE,
    CONSTRAINT ck_notifications_title CHECK (TRIM(title) <> ''),
    CONSTRAINT ck_notifications_message CHECK (TRIM(message) <> ''),
    CONSTRAINT ck_notifications_type CHECK (notification_type IN (
        'VERIFICATION_DECISION',
        'SUBMISSION_DECISION',
        'REPRESENTATIVE_DECISION',
        'REPORT_OUTCOME',
        'APPLICATION_RECEIVED',
        'APPLICATION_STATUS',
        'JOB_CLOSED',
        'SECURITY_EVENT'
    )),
    CONSTRAINT ck_notifications_entity CHECK (
        (related_entity_type IS NULL AND related_entity_id IS NULL)
        OR
        (related_entity_type IN (
            'SUBMISSION', 'VERIFICATION', 'JOB', 'APPLICATION', 'ASSIGNMENT', 'REPORT', 'ACCOUNT'
        ) AND related_entity_id IS NOT NULL AND related_entity_id > 0)
    ),
    CONSTRAINT ck_notifications_plain_text CHECK (
        title !~ '[<>]' AND message !~ '[<>]'
    )
);

-- ================================================================
-- 10. SUPPORTING INDEXES
-- ================================================================

CREATE INDEX ix_password_reset_user_state
    ON password_reset_tokens (user_id, expires_at, used_at, revoked_at);
CREATE INDEX ix_companies_industry_city ON companies (industry, headquarters_city);
CREATE INDEX ix_company_benefits_benefit ON company_benefits (benefit_id);
CREATE INDEX ix_emp_verify_company_status ON employment_verifications (company_id, verification_status);
CREATE INDEX ix_emp_verify_employee ON employment_verifications (employee_id);
CREATE INDEX ix_emp_verify_reviewer ON employment_verifications (reviewed_by);
CREATE INDEX ix_emp_verify_scope_status
    ON employment_verifications (employee_id, company_id, role_id, verification_status);
CREATE INDEX ix_submissions_user ON submissions (user_id);
CREATE INDEX ix_submissions_company_status ON submissions (company_id, submission_status);
CREATE INDEX ix_submissions_verify_status ON submissions (verification_status);
CREATE INDEX ix_salary_role ON salary_submissions (role_id);
CREATE INDEX ix_review_role ON company_reviews (role_id);
CREATE INDEX ix_interview_role ON interview_experiences (role_id);
CREATE INDEX ix_reports_submission_status ON reports (submission_id, report_status);
CREATE INDEX ix_reports_resolver ON reports (resolved_by);
CREATE INDEX ix_mod_actions_submission_time ON moderation_actions (submission_id, action_at);
CREATE INDEX ix_mod_actions_moderator ON moderation_actions (moderator_user_id);
CREATE UNIQUE INDEX uk_company_rep_open_scope
    ON company_representatives (user_id, company_id)
    WHERE assignment_status IN ('PENDING', 'ACTIVE');
CREATE INDEX ix_company_rep_company_status
    ON company_representatives (company_id, assignment_status);
CREATE INDEX ix_company_rep_user_status
    ON company_representatives (user_id, assignment_status);
CREATE INDEX ix_company_rep_status_created
    ON company_representatives (assignment_status, created_at);
CREATE INDEX ix_rep_action_assignment_time
    ON representative_assignment_actions (assignment_id, action_at);
CREATE INDEX ix_rep_action_actor
    ON representative_assignment_actions (actor_user_id);
CREATE INDEX ix_job_company_status ON job_postings (company_id, job_status);
CREATE INDEX ix_job_status_deadline ON job_postings (job_status, application_deadline);
CREATE INDEX ix_job_role ON job_postings (role_id);
CREATE INDEX ix_job_creator ON job_postings (created_by_user_id);
CREATE INDEX ix_job_assignment ON job_postings (created_by_assignment_id);
CREATE INDEX ix_job_published_at ON job_postings (published_at DESC);
CREATE INDEX ix_application_job_status ON job_applications (job_id, application_status);
CREATE INDEX ix_application_applicant ON job_applications (applicant_user_id, submitted_at DESC);
CREATE INDEX ix_application_reviewer ON job_applications (reviewed_by);
CREATE INDEX ix_application_history_application
    ON job_application_status_history (application_id, action_at);
CREATE INDEX ix_application_history_actor
    ON job_application_status_history (actor_user_id);
CREATE INDEX ix_announcements_window ON announcements (is_active, starts_at, ends_at);
CREATE INDEX ix_announcements_author ON announcements (created_by);
CREATE INDEX ix_notifications_owner_time
    ON notifications (user_id, created_at DESC, notification_id DESC);
CREATE INDEX ix_notifications_unread ON notifications (user_id) WHERE read_at IS NULL;

-- ================================================================
-- 11. PUBLIC AND ANALYTICAL VIEWS
-- ================================================================

-- Public views omit account identity and private workflow information.
CREATE OR REPLACE VIEW vw_public_companies AS
SELECT company_id,
       company_name,
       industry,
       headquarters_city,
       country,
       website,
       company_size,
       description
FROM companies;

CREATE OR REPLACE VIEW vw_public_approved_reviews AS
SELECT s.submission_id,
       s.company_id,
       c.company_name,
       r.role_id,
       jr.role_name,
       r.review_title,
       r.overall_rating,
       r.work_life_balance_rating,
       r.career_growth_rating,
       r.management_rating,
       r.culture_rating,
       r.pros,
       r.cons,
       r.advice_to_management,
       r.employment_status,
       r.review_date,
       s.verification_status,
       s.submitted_at
FROM submissions s
JOIN company_reviews r ON r.submission_id = s.submission_id
JOIN companies c ON c.company_id = s.company_id
LEFT JOIN job_roles jr ON jr.role_id = r.role_id
WHERE s.submission_type = 'REVIEW'
  AND s.submission_status = 'APPROVED';

CREATE OR REPLACE VIEW vw_verified_salary_summary AS
SELECT s.company_id,
       c.company_name,
       ss.role_id,
       jr.role_name,
       ss.currency,
       ss.pay_period,
       MIN(ss.base_salary) AS minimum_salary,
       MAX(ss.base_salary) AS maximum_salary,
       ROUND(AVG(ss.base_salary), 2) AS average_salary,
       COUNT(*) AS contribution_count
FROM submissions s
JOIN salary_submissions ss ON ss.submission_id = s.submission_id
JOIN companies c ON c.company_id = s.company_id
JOIN job_roles jr ON jr.role_id = ss.role_id
WHERE s.submission_type = 'SALARY'
  AND s.submission_status = 'APPROVED'
  AND s.verification_status = 'VERIFIED'
GROUP BY s.company_id, c.company_name, ss.role_id, jr.role_name,
         ss.currency, ss.pay_period;

CREATE OR REPLACE VIEW vw_community_salary_summary AS
SELECT s.company_id,
       c.company_name,
       ss.role_id,
       jr.role_name,
       ss.currency,
       ss.pay_period,
       MIN(ss.base_salary) AS minimum_salary,
       MAX(ss.base_salary) AS maximum_salary,
       ROUND(AVG(ss.base_salary), 2) AS average_salary,
       COUNT(*) AS contribution_count
FROM submissions s
JOIN salary_submissions ss ON ss.submission_id = s.submission_id
JOIN companies c ON c.company_id = s.company_id
JOIN job_roles jr ON jr.role_id = ss.role_id
WHERE s.submission_type = 'SALARY'
  AND s.submission_status = 'APPROVED'
GROUP BY s.company_id, c.company_name, ss.role_id, jr.role_name,
         ss.currency, ss.pay_period;

-- Published, still-open jobs only. Draft, closed and archived rows never
-- appear, and no applicant or private representative data is exposed.
CREATE OR REPLACE VIEW vw_public_open_jobs AS
SELECT jp.job_id,
       jp.company_id,
       c.company_name,
       c.industry,
       jp.role_id,
       jr.role_name,
       jr.role_category,
       jp.title,
       jp.description,
       jp.requirements,
       jp.location,
       jp.employment_type,
       jp.work_mode,
       jp.salary_min,
       jp.salary_max,
       jp.salary_currency,
       jp.salary_period,
       jp.application_deadline,
       jp.published_at
FROM job_postings jp
JOIN companies c ON c.company_id = jp.company_id
LEFT JOIN job_roles jr ON jr.role_id = jp.role_id
WHERE jp.job_status = 'PUBLISHED'
  AND jp.application_deadline >= CURRENT_DATE;

-- Express is the only application database client. Supabase browser roles
-- receive no direct table/view access when those roles exist.
DO $saple_security$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN
        REVOKE ALL ON ALL TABLES IN SCHEMA public FROM anon;
        REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM anon;
        ALTER DEFAULT PRIVILEGES IN SCHEMA public
            REVOKE ALL ON TABLES FROM anon;
        ALTER DEFAULT PRIVILEGES IN SCHEMA public
            REVOKE ALL ON SEQUENCES FROM anon;
    END IF;

    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN
        REVOKE ALL ON ALL TABLES IN SCHEMA public FROM authenticated;
        REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM authenticated;
        ALTER DEFAULT PRIVILEGES IN SCHEMA public
            REVOKE ALL ON TABLES FROM authenticated;
        ALTER DEFAULT PRIVILEGES IN SCHEMA public
            REVOKE ALL ON SEQUENCES FROM authenticated;
    END IF;
END
$saple_security$;

COMMIT;
