-- Saple database schema for Oracle Database 19c

-- ================================================================
-- 1. Optional cleanup/drop section
-- Run this file to rebuild the Saple objects in the current schema.
-- Each block ignores only ORA-00942 (table or view does not exist).
-- ================================================================

BEGIN
    EXECUTE IMMEDIATE 'DROP VIEW vw_verified_salary_summary';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP VIEW vw_community_salary_summary';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP VIEW vw_public_approved_reviews';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP VIEW vw_public_companies';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE moderation_actions CASCADE CONSTRAINTS PURGE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE reports CASCADE CONSTRAINTS PURGE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE interview_experiences CASCADE CONSTRAINTS PURGE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE company_reviews CASCADE CONSTRAINTS PURGE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE salary_submissions CASCADE CONSTRAINTS PURGE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE submissions CASCADE CONSTRAINTS PURGE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE employment_verifications CASCADE CONSTRAINTS PURGE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE company_benefits CASCADE CONSTRAINTS PURGE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE benefits CASCADE CONSTRAINTS PURGE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE job_roles CASCADE CONSTRAINTS PURGE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE companies CASCADE CONSTRAINTS PURGE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE employees CASCADE CONSTRAINTS PURGE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE users CASCADE CONSTRAINTS PURGE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

-- ================================================================
-- 2. Core account tables
-- ================================================================

CREATE TABLE users (
    user_id        NUMBER GENERATED BY DEFAULT AS IDENTITY,
    full_name      VARCHAR2(120) NOT NULL,
    email          VARCHAR2(254) NOT NULL,
    -- Sensitive: password_hash must never be returned by public APIs.
    password_hash  VARCHAR2(255) NOT NULL,
    user_type      VARCHAR2(10) DEFAULT 'NORMAL' NOT NULL,
    account_role   VARCHAR2(10) DEFAULT 'USER' NOT NULL,
    account_status VARCHAR2(15) DEFAULT 'ACTIVE' NOT NULL,
    created_at     TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at     TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (user_id),
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT ck_users_full_name CHECK (TRIM(full_name) IS NOT NULL),
    CONSTRAINT ck_users_email CHECK (TRIM(email) IS NOT NULL),
    CONSTRAINT ck_users_password_hash CHECK (LENGTH(password_hash) >= 20),
    CONSTRAINT ck_users_type CHECK (user_type IN ('NORMAL', 'EMPLOYEE')),
    CONSTRAINT ck_users_role CHECK (account_role IN ('USER', 'ADMIN')),
    CONSTRAINT ck_users_status CHECK (account_status IN ('ACTIVE', 'SUSPENDED', 'DEACTIVATED'))
);

CREATE TABLE employees (
    employee_id       NUMBER GENERATED BY DEFAULT AS IDENTITY,
    user_id           NUMBER NOT NULL,
    employment_status VARCHAR2(10) NOT NULL,
    created_at        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_employees PRIMARY KEY (employee_id),
    CONSTRAINT uk_employees_user UNIQUE (user_id),
    CONSTRAINT fk_employees_user FOREIGN KEY (user_id)
        REFERENCES users (user_id) ON DELETE CASCADE,
    CONSTRAINT ck_employees_status CHECK (employment_status IN ('CURRENT', 'FORMER'))
);

-- ================================================================
-- 3. Company reference tables
-- ================================================================

CREATE TABLE companies (
    company_id       NUMBER GENERATED BY DEFAULT AS IDENTITY,
    company_name     VARCHAR2(150) NOT NULL,
    industry         VARCHAR2(100) NOT NULL,
    headquarters_city VARCHAR2(100) NOT NULL,
    country          VARCHAR2(100) NOT NULL,
    website          VARCHAR2(255),
    company_size     VARCHAR2(30),
    description      CLOB,
    created_at       TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at       TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_companies PRIMARY KEY (company_id),
    CONSTRAINT uk_companies_name UNIQUE (company_name),
    CONSTRAINT ck_companies_name CHECK (TRIM(company_name) IS NOT NULL),
    CONSTRAINT ck_companies_industry CHECK (TRIM(industry) IS NOT NULL),
    CONSTRAINT ck_companies_city CHECK (TRIM(headquarters_city) IS NOT NULL),
    CONSTRAINT ck_companies_country CHECK (TRIM(country) IS NOT NULL)
);

CREATE TABLE job_roles (
    role_id       NUMBER GENERATED BY DEFAULT AS IDENTITY,
    role_name     VARCHAR2(120) NOT NULL,
    role_category VARCHAR2(100),
    description   VARCHAR2(500),
    CONSTRAINT pk_job_roles PRIMARY KEY (role_id),
    CONSTRAINT uk_job_roles_name UNIQUE (role_name),
    CONSTRAINT ck_job_roles_name CHECK (TRIM(role_name) IS NOT NULL)
);

CREATE TABLE benefits (
    benefit_id       NUMBER GENERATED BY DEFAULT AS IDENTITY,
    benefit_name     VARCHAR2(120) NOT NULL,
    benefit_category VARCHAR2(100),
    description      VARCHAR2(500),
    CONSTRAINT pk_benefits PRIMARY KEY (benefit_id),
    CONSTRAINT uk_benefits_name UNIQUE (benefit_name),
    CONSTRAINT ck_benefits_name CHECK (TRIM(benefit_name) IS NOT NULL)
);

CREATE TABLE company_benefits (
    company_id  NUMBER NOT NULL,
    benefit_id  NUMBER NOT NULL,
    details     VARCHAR2(500),
    eligibility VARCHAR2(250),
    last_updated TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_company_benefits PRIMARY KEY (company_id, benefit_id),
    CONSTRAINT fk_company_benefits_company FOREIGN KEY (company_id)
        REFERENCES companies (company_id) ON DELETE CASCADE,
    CONSTRAINT fk_company_benefits_benefit FOREIGN KEY (benefit_id)
        REFERENCES benefits (benefit_id) ON DELETE CASCADE
);

-- ================================================================
-- 4. Employee verification tables
-- ================================================================

CREATE TABLE employment_verifications (
    verification_id     NUMBER GENERATED BY DEFAULT AS IDENTITY,
    employee_id         NUMBER NOT NULL,
    company_id          NUMBER NOT NULL,
    verification_method VARCHAR2(30) NOT NULL,
    -- Sensitive: company_email is private and must not be returned publicly.
    company_email       VARCHAR2(254),
    proof_type          VARCHAR2(30),
    -- Sensitive: store only a safe file reference/token, never document contents.
    proof_reference     VARCHAR2(255),
    verification_status VARCHAR2(10) DEFAULT 'PENDING' NOT NULL,
    requested_at        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    reviewed_at         TIMESTAMP,
    expires_at          TIMESTAMP,
    -- Sensitive: rejection_reason is for internal review only.
    rejection_reason    VARCHAR2(500),
    reviewed_by         NUMBER,
    CONSTRAINT pk_employment_verifications PRIMARY KEY (verification_id),
    CONSTRAINT fk_emp_verify_employee FOREIGN KEY (employee_id)
        REFERENCES employees (employee_id) ON DELETE CASCADE,
    CONSTRAINT fk_emp_verify_company FOREIGN KEY (company_id)
        REFERENCES companies (company_id) ON DELETE CASCADE,
    CONSTRAINT fk_emp_verify_reviewer FOREIGN KEY (reviewed_by)
        REFERENCES users (user_id),
    CONSTRAINT ck_emp_verify_method CHECK (verification_method IN ('COMPANY_EMAIL_OTP', 'DOCUMENT')),
    CONSTRAINT ck_emp_verify_status CHECK (verification_status IN ('VERIFIED', 'PENDING', 'REJECTED', 'EXPIRED')),
    CONSTRAINT ck_emp_verify_proof CHECK (
        (verification_method = 'COMPANY_EMAIL_OTP' AND company_email IS NOT NULL AND proof_reference IS NULL)
        OR
        (verification_method = 'DOCUMENT' AND proof_type IS NOT NULL AND proof_reference IS NOT NULL AND company_email IS NULL)
    ),
    CONSTRAINT ck_emp_verify_review CHECK (
        (verification_status = 'PENDING' AND reviewed_at IS NULL AND reviewed_by IS NULL)
        OR
        (verification_status <> 'PENDING' AND reviewed_at IS NOT NULL AND reviewed_by IS NOT NULL)
    ),
    CONSTRAINT ck_emp_verify_rejection CHECK (
        verification_status = 'REJECTED' OR rejection_reason IS NULL
    )
);

-- ================================================================
-- 5. Submission parent table
-- ================================================================

CREATE TABLE submissions (
    submission_id      NUMBER GENERATED BY DEFAULT AS IDENTITY,
    user_id            NUMBER NOT NULL,
    company_id         NUMBER NOT NULL,
    submission_type    VARCHAR2(10) NOT NULL,
    is_anonymous       NUMBER(1) DEFAULT 1 NOT NULL,
    submission_status  VARCHAR2(10) DEFAULT 'PENDING' NOT NULL,
    verification_status VARCHAR2(10) DEFAULT 'UNVERIFIED' NOT NULL,
    submitted_at       TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    approved_at        TIMESTAMP,
    updated_at         TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_submissions PRIMARY KEY (submission_id),
    CONSTRAINT fk_submissions_user FOREIGN KEY (user_id)
        REFERENCES users (user_id),
    CONSTRAINT fk_submissions_company FOREIGN KEY (company_id)
        REFERENCES companies (company_id),
    CONSTRAINT ck_submissions_type CHECK (submission_type IN ('SALARY', 'REVIEW', 'INTERVIEW')),
    CONSTRAINT ck_submissions_anonymous CHECK (is_anonymous IN (0, 1)),
    CONSTRAINT ck_submissions_status CHECK (submission_status IN ('PENDING', 'APPROVED', 'FLAGGED', 'REJECTED')),
    CONSTRAINT ck_submissions_verify CHECK (verification_status IN ('VERIFIED', 'UNVERIFIED', 'PENDING', 'REJECTED')),
    CONSTRAINT ck_submissions_approved_at CHECK (
        (submission_status = 'APPROVED' AND approved_at IS NOT NULL)
        OR
        (submission_status <> 'APPROVED' AND approved_at IS NULL)
    )
);

-- ================================================================
-- 6. Submission subtype tables
-- ================================================================

CREATE TABLE salary_submissions (
    submission_id          NUMBER,
    role_id                NUMBER NOT NULL,
    base_salary            NUMBER(12,2) NOT NULL,
    additional_compensation NUMBER(12,2),
    currency               VARCHAR2(3) DEFAULT 'BDT' NOT NULL,
    pay_period             VARCHAR2(10) NOT NULL,
    years_of_experience    NUMBER(4,1) NOT NULL,
    employment_type        VARCHAR2(15) NOT NULL,
    work_mode              VARCHAR2(10) NOT NULL,
    salary_year            NUMBER(4) NOT NULL,
    CONSTRAINT pk_salary_submissions PRIMARY KEY (submission_id),
    CONSTRAINT fk_salary_submission FOREIGN KEY (submission_id)
        REFERENCES submissions (submission_id) ON DELETE CASCADE,
    CONSTRAINT fk_salary_role FOREIGN KEY (role_id)
        REFERENCES job_roles (role_id),
    CONSTRAINT ck_salary_base CHECK (base_salary > 0 AND base_salary <= 9999999999.99),
    CONSTRAINT ck_salary_additional CHECK (additional_compensation IS NULL OR additional_compensation >= 0),
    CONSTRAINT ck_salary_currency CHECK (LENGTH(currency) = 3 AND currency = UPPER(currency)),
    CONSTRAINT ck_salary_period CHECK (pay_period IN ('MONTHLY', 'YEARLY')),
    CONSTRAINT ck_salary_experience CHECK (years_of_experience BETWEEN 0 AND 60),
    CONSTRAINT ck_salary_employment CHECK (employment_type IN ('FULL_TIME', 'PART_TIME', 'CONTRACT', 'INTERN')),
    CONSTRAINT ck_salary_work_mode CHECK (work_mode IN ('ONSITE', 'HYBRID', 'REMOTE')),
    CONSTRAINT ck_salary_year CHECK (salary_year BETWEEN 2000 AND 2100)
);

CREATE TABLE company_reviews (
    submission_id           NUMBER,
    role_id                 NUMBER,
    review_title            VARCHAR2(200) NOT NULL,
    overall_rating          NUMBER(2,1) NOT NULL,
    work_life_balance_rating NUMBER(2,1) NOT NULL,
    career_growth_rating    NUMBER(2,1) NOT NULL,
    management_rating       NUMBER(2,1) NOT NULL,
    culture_rating          NUMBER(2,1) NOT NULL,
    pros                    CLOB NOT NULL,
    cons                    CLOB NOT NULL,
    advice_to_management    CLOB,
    employment_status       VARCHAR2(10) NOT NULL,
    review_date             DATE NOT NULL,
    CONSTRAINT pk_company_reviews PRIMARY KEY (submission_id),
    CONSTRAINT fk_review_submission FOREIGN KEY (submission_id)
        REFERENCES submissions (submission_id) ON DELETE CASCADE,
    CONSTRAINT fk_review_role FOREIGN KEY (role_id)
        REFERENCES job_roles (role_id),
    CONSTRAINT ck_review_title CHECK (TRIM(review_title) IS NOT NULL),
    CONSTRAINT ck_review_overall CHECK (overall_rating BETWEEN 1 AND 5),
    CONSTRAINT ck_review_work_life CHECK (work_life_balance_rating BETWEEN 1 AND 5),
    CONSTRAINT ck_review_growth CHECK (career_growth_rating BETWEEN 1 AND 5),
    CONSTRAINT ck_review_management CHECK (management_rating BETWEEN 1 AND 5),
    CONSTRAINT ck_review_culture CHECK (culture_rating BETWEEN 1 AND 5),
    CONSTRAINT ck_review_pros CHECK (DBMS_LOB.GETLENGTH(pros) > 0),
    CONSTRAINT ck_review_cons CHECK (DBMS_LOB.GETLENGTH(cons) > 0),
    CONSTRAINT ck_review_employment CHECK (employment_status IN ('CURRENT', 'FORMER'))
);

CREATE TABLE interview_experiences (
    submission_id      NUMBER,
    role_id            NUMBER NOT NULL,
    interview_date     DATE NOT NULL,
    difficulty_level   VARCHAR2(10) NOT NULL,
    rounds_count       NUMBER(2) NOT NULL,
    interview_mode     VARCHAR2(10) NOT NULL,
    result_status      VARCHAR2(10) NOT NULL,
    duration_days      NUMBER(3) NOT NULL,
    process_description CLOB NOT NULL,
    questions_summary  CLOB,
    CONSTRAINT pk_interview_experiences PRIMARY KEY (submission_id),
    CONSTRAINT fk_interview_submission FOREIGN KEY (submission_id)
        REFERENCES submissions (submission_id) ON DELETE CASCADE,
    CONSTRAINT fk_interview_role FOREIGN KEY (role_id)
        REFERENCES job_roles (role_id),
    CONSTRAINT ck_interview_difficulty CHECK (difficulty_level IN ('EASY', 'MEDIUM', 'HARD')),
    CONSTRAINT ck_interview_rounds CHECK (rounds_count BETWEEN 1 AND 20),
    CONSTRAINT ck_interview_mode CHECK (interview_mode IN ('ONLINE', 'ONSITE', 'HYBRID')),
    CONSTRAINT ck_interview_result CHECK (result_status IN ('OFFERED', 'REJECTED', 'PENDING', 'WITHDREW')),
    CONSTRAINT ck_interview_duration CHECK (duration_days BETWEEN 0 AND 365),
    CONSTRAINT ck_interview_process CHECK (DBMS_LOB.GETLENGTH(process_description) > 0)
);

-- ================================================================
-- 7. Reporting and moderation tables
-- ================================================================

CREATE TABLE reports (
    report_id           NUMBER GENERATED BY DEFAULT AS IDENTITY,
    -- Sensitive: reporter identity must not be exposed by public APIs.
    reporter_user_id    NUMBER NOT NULL,
    submission_id       NUMBER NOT NULL,
    reason_category     VARCHAR2(15) NOT NULL,
    report_description  VARCHAR2(1000),
    report_status       VARCHAR2(10) DEFAULT 'OPEN' NOT NULL,
    reported_at         TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    resolved_at         TIMESTAMP,
    -- Sensitive: resolution_note is internal moderation information.
    resolution_note     VARCHAR2(1000),
    resolved_by         NUMBER,
    CONSTRAINT pk_reports PRIMARY KEY (report_id),
    CONSTRAINT uk_reports_reporter_submission UNIQUE (reporter_user_id, submission_id),
    CONSTRAINT fk_reports_reporter FOREIGN KEY (reporter_user_id)
        REFERENCES users (user_id),
    CONSTRAINT fk_reports_submission FOREIGN KEY (submission_id)
        REFERENCES submissions (submission_id) ON DELETE CASCADE,
    CONSTRAINT fk_reports_resolver FOREIGN KEY (resolved_by)
        REFERENCES users (user_id),
    CONSTRAINT ck_reports_reason CHECK (reason_category IN ('FAKE_DATA', 'DEFAMATION', 'SPAM', 'PRIVACY', 'OTHER')),
    CONSTRAINT ck_reports_status CHECK (report_status IN ('OPEN', 'REVIEWING', 'RESOLVED', 'DISMISSED')),
    CONSTRAINT ck_reports_resolution CHECK (
        (report_status IN ('OPEN', 'REVIEWING') AND resolved_at IS NULL AND resolved_by IS NULL)
        OR
        (report_status IN ('RESOLVED', 'DISMISSED') AND resolved_at IS NOT NULL AND resolved_by IS NOT NULL)
    )
);

CREATE TABLE moderation_actions (
    action_id          NUMBER GENERATED BY DEFAULT AS IDENTITY,
    submission_id      NUMBER NOT NULL,
    moderator_user_id  NUMBER NOT NULL,
    action_type        VARCHAR2(15) NOT NULL,
    previous_status    VARCHAR2(10),
    new_status         VARCHAR2(10) NOT NULL,
    -- Sensitive: action_note is internal moderation information.
    action_note        VARCHAR2(1000),
    action_at          TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_moderation_actions PRIMARY KEY (action_id),
    CONSTRAINT fk_mod_actions_submission FOREIGN KEY (submission_id)
        REFERENCES submissions (submission_id) ON DELETE CASCADE,
    CONSTRAINT fk_mod_actions_moderator FOREIGN KEY (moderator_user_id)
        REFERENCES users (user_id),
    CONSTRAINT ck_mod_actions_type CHECK (action_type IN ('APPROVE', 'REJECT', 'FLAG', 'UNFLAG', 'EDIT_STATUS')),
    CONSTRAINT ck_mod_actions_previous CHECK (previous_status IS NULL OR previous_status IN ('PENDING', 'APPROVED', 'FLAGGED', 'REJECTED')),
    CONSTRAINT ck_mod_actions_new CHECK (new_status IN ('PENDING', 'APPROVED', 'FLAGGED', 'REJECTED'))
);

-- ================================================================
-- 8. Useful indexes (PK and UNIQUE indexes are not duplicated)
-- ================================================================

CREATE INDEX ix_companies_industry_city ON companies (industry, headquarters_city);
CREATE INDEX ix_company_benefits_benefit ON company_benefits (benefit_id);
CREATE INDEX ix_emp_verify_company_status ON employment_verifications (company_id, verification_status);
CREATE INDEX ix_emp_verify_employee ON employment_verifications (employee_id);
CREATE INDEX ix_emp_verify_reviewer ON employment_verifications (reviewed_by);
CREATE INDEX ix_submissions_user ON submissions (user_id);
CREATE INDEX ix_submissions_company_status ON submissions (company_id, submission_status);
CREATE INDEX ix_submissions_verify_status ON submissions (verification_status);
CREATE INDEX ix_salary_role ON salary_submissions (role_id);
CREATE INDEX ix_review_role ON company_reviews (role_id);
CREATE INDEX ix_interview_role ON interview_experiences (role_id);
CREATE INDEX ix_reports_submission_status ON reports (submission_id, report_status);
CREATE INDEX ix_reports_resolver ON reports (resolved_by);
CREATE INDEX ix_mod_actions_submission_time ON moderation_actions (submission_id, action_at);
CREATE INDEX ix_mod_actions_moderator ON moderation_actions (moderator_user_id);

-- ================================================================
-- 9. Public and analytical views
-- These views intentionally omit account data, private verification details,
-- reporter identity, rejection reasons, proof references, and internal notes.
-- ================================================================

CREATE OR REPLACE VIEW vw_public_companies AS
SELECT company_id,
       company_name,
       industry,
       headquarters_city,
       country,
       website,
       company_size,
       description
FROM companies;

CREATE OR REPLACE VIEW vw_public_approved_reviews AS
SELECT s.submission_id,
       s.company_id,
       c.company_name,
       r.role_id,
       jr.role_name,
       r.review_title,
       r.overall_rating,
       r.work_life_balance_rating,
       r.career_growth_rating,
       r.management_rating,
       r.culture_rating,
       r.pros,
       r.cons,
       r.advice_to_management,
       r.employment_status,
       r.review_date,
       s.verification_status,
       s.submitted_at
FROM submissions s
JOIN company_reviews r ON r.submission_id = s.submission_id
JOIN companies c ON c.company_id = s.company_id
LEFT JOIN job_roles jr ON jr.role_id = r.role_id
WHERE s.submission_type = 'REVIEW'
  AND s.submission_status = 'APPROVED';

CREATE OR REPLACE VIEW vw_verified_salary_summary AS
SELECT s.company_id,
       c.company_name,
       ss.role_id,
       jr.role_name,
       ss.currency,
       ss.pay_period,
       MIN(ss.base_salary) AS minimum_salary,
       MAX(ss.base_salary) AS maximum_salary,
       ROUND(AVG(ss.base_salary), 2) AS average_salary,
       COUNT(*) AS contribution_count
FROM submissions s
JOIN salary_submissions ss ON ss.submission_id = s.submission_id
JOIN companies c ON c.company_id = s.company_id
JOIN job_roles jr ON jr.role_id = ss.role_id
WHERE s.submission_type = 'SALARY'
  AND s.submission_status = 'APPROVED'
  AND s.verification_status = 'VERIFIED'
GROUP BY s.company_id, c.company_name, ss.role_id, jr.role_name,
         ss.currency, ss.pay_period;

CREATE OR REPLACE VIEW vw_community_salary_summary AS
SELECT s.company_id,
       c.company_name,
       ss.role_id,
       jr.role_name,
       ss.currency,
       ss.pay_period,
       MIN(ss.base_salary) AS minimum_salary,
       MAX(ss.base_salary) AS maximum_salary,
       ROUND(AVG(ss.base_salary), 2) AS average_salary,
       COUNT(*) AS contribution_count
FROM submissions s
JOIN salary_submissions ss ON ss.submission_id = s.submission_id
JOIN companies c ON c.company_id = s.company_id
JOIN job_roles jr ON jr.role_id = ss.role_id
WHERE s.submission_type = 'SALARY'
  AND s.submission_status = 'APPROVED'
GROUP BY s.company_id, c.company_name, ss.role_id, jr.role_name,
         ss.currency, ss.pay_period;

-- ================================================================
-- 10. Important business rules
-- ================================================================
-- The application enforces these cross-table rules:
-- * employees.user_id belongs to a users row whose user_type is EMPLOYEE.
-- * reviewed_by, resolved_by, and moderator_user_id identify ACTIVE ADMIN users.
-- * current employees use COMPANY_EMAIL_OTP and former employees use DOCUMENT.
-- * at most one PENDING verification exists per employee/company at a time;
--   history is retained, so a normal UNIQUE constraint would be too restrictive.
-- * each subtype row matches submissions.submission_type.
-- * submission verification is valid for the submission's specific company.
-- * timestamps and allowed status transitions follow the application workflow.
-- * moderation_actions rows are append-only during normal application operation.
