-- Saple password-reset token migration for Oracle Database 19c
-- Run once after 02_create_tables.sql. It is safe to run before or after
-- the sample/reference data scripts because it adds no sample rows.

CREATE TABLE password_reset_tokens (
    reset_token_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    user_id        NUMBER NOT NULL,
    -- Sensitive: store only the 64-character SHA-256 hash, never the raw token.
    token_hash     VARCHAR2(64) NOT NULL,
    expires_at     TIMESTAMP NOT NULL,
    used_at        TIMESTAMP,
    revoked_at     TIMESTAMP,
    created_at     TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_password_reset_tokens PRIMARY KEY (reset_token_id),
    CONSTRAINT uk_password_reset_token_hash UNIQUE (token_hash),
    CONSTRAINT fk_password_reset_user FOREIGN KEY (user_id)
        REFERENCES users (user_id) ON DELETE CASCADE,
    CONSTRAINT ck_password_reset_token_hash CHECK (LENGTH(token_hash) = 64),
    CONSTRAINT ck_password_reset_expiry CHECK (expires_at > created_at),
    CONSTRAINT ck_password_reset_state CHECK (used_at IS NULL OR revoked_at IS NULL)
);

CREATE INDEX ix_password_reset_user_state
    ON password_reset_tokens (user_id, expires_at, used_at, revoked_at);

COMMENT ON TABLE password_reset_tokens IS
    'Single-use, expiring password-reset token hashes for Saple accounts.';
COMMENT ON COLUMN password_reset_tokens.token_hash IS
    'SHA-256 hash of a cryptographically random token; the raw token is never stored.';

COMMIT;
