-- SAPLE MIGRATION 001 - ACCOUNT ROLES AND COMPANY REPRESENTATIVES
-- Additive and non-destructive. Safe to run once on an existing Supabase project.
-- Re-running is harmless: every object is guarded.
--
-- What it does:
--   1. Widens USERS.ACCOUNT_ROLE and allows the COMPANY_REPRESENTATIVE role.
--   2. Adds COMPANY_REPRESENTATIVES, the admin-approved company scope assignment.
--   3. Adds REPRESENTATIVE_ASSIGNMENT_ACTIONS, the immutable decision history.
--
-- No existing row is modified: every current account keeps USER or ADMIN.

BEGIN;

-- ================================================================
-- 1. CONTROLLED ACCOUNT ROLE
-- ================================================================

ALTER TABLE users
    ALTER COLUMN account_role TYPE VARCHAR(25);

ALTER TABLE users
    DROP CONSTRAINT IF EXISTS ck_users_role;

ALTER TABLE users
    ADD CONSTRAINT ck_users_role
    CHECK (account_role IN ('USER', 'ADMIN', 'COMPANY_REPRESENTATIVE'));

-- ================================================================
-- 2. COMPANY REPRESENTATIVE ASSIGNMENTS
-- ================================================================

-- COMPANY_REPRESENTATIVES binds one account to one company with an
-- administrator-controlled lifecycle. Public registration can never write here.
CREATE TABLE IF NOT EXISTS company_representatives (
    assignment_id     BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id           BIGINT NOT NULL,
    company_id        BIGINT NOT NULL,
    job_title         VARCHAR(120),
    assignment_status VARCHAR(10) DEFAULT 'PENDING' NOT NULL,
    request_note      VARCHAR(1000),
    decision_note     VARCHAR(1000),
    approved_by       BIGINT,
    approved_at       TIMESTAMPTZ,
    revoked_by        BIGINT,
    revoked_at        TIMESTAMPTZ,
    created_at        TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at        TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_company_representatives PRIMARY KEY (assignment_id),
    CONSTRAINT fk_company_rep_user FOREIGN KEY (user_id)
        REFERENCES users (user_id) ON DELETE CASCADE,
    CONSTRAINT fk_company_rep_company FOREIGN KEY (company_id)
        REFERENCES companies (company_id) ON DELETE RESTRICT,
    CONSTRAINT fk_company_rep_approver FOREIGN KEY (approved_by)
        REFERENCES users (user_id),
    CONSTRAINT fk_company_rep_revoker FOREIGN KEY (revoked_by)
        REFERENCES users (user_id),
    CONSTRAINT ck_company_rep_status
        CHECK (assignment_status IN ('PENDING', 'ACTIVE', 'REJECTED', 'REVOKED')),
    CONSTRAINT ck_company_rep_job_title
        CHECK (job_title IS NULL OR TRIM(job_title) <> ''),
    -- An approved assignment always records who approved it and when.
    CONSTRAINT ck_company_rep_approval CHECK (
        (assignment_status = 'PENDING' AND approved_by IS NULL AND approved_at IS NULL)
        OR
        (assignment_status IN ('ACTIVE', 'REVOKED') AND approved_by IS NOT NULL AND approved_at IS NOT NULL)
        OR
        (assignment_status = 'REJECTED' AND approved_by IS NULL AND approved_at IS NULL)
    ),
    -- Only a revoked assignment carries revocation identity.
    CONSTRAINT ck_company_rep_revocation CHECK (
        (assignment_status = 'REVOKED' AND revoked_by IS NOT NULL AND revoked_at IS NOT NULL)
        OR
        (assignment_status <> 'REVOKED' AND revoked_by IS NULL AND revoked_at IS NULL)
    ),
    -- Rejection and revocation must explain themselves.
    CONSTRAINT ck_company_rep_decision_note CHECK (
        assignment_status NOT IN ('REJECTED', 'REVOKED') OR decision_note IS NOT NULL
    )
);

-- One open or active scope per account and company. Closed rows stay for audit.
CREATE UNIQUE INDEX IF NOT EXISTS uk_company_rep_open_scope
    ON company_representatives (user_id, company_id)
    WHERE assignment_status IN ('PENDING', 'ACTIVE');

CREATE INDEX IF NOT EXISTS ix_company_rep_company_status
    ON company_representatives (company_id, assignment_status);
CREATE INDEX IF NOT EXISTS ix_company_rep_user_status
    ON company_representatives (user_id, assignment_status);
CREATE INDEX IF NOT EXISTS ix_company_rep_status_created
    ON company_representatives (assignment_status, created_at);

-- ================================================================
-- 3. IMMUTABLE ASSIGNMENT DECISION HISTORY
-- ================================================================

CREATE TABLE IF NOT EXISTS representative_assignment_actions (
    action_id       BIGINT GENERATED BY DEFAULT AS IDENTITY,
    assignment_id   BIGINT NOT NULL,
    actor_user_id   BIGINT NOT NULL,
    action_type     VARCHAR(10) NOT NULL,
    previous_status VARCHAR(10),
    new_status      VARCHAR(10) NOT NULL,
    action_note     VARCHAR(1000),
    action_at       TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_representative_assignment_actions PRIMARY KEY (action_id),
    CONSTRAINT fk_rep_action_assignment FOREIGN KEY (assignment_id)
        REFERENCES company_representatives (assignment_id) ON DELETE RESTRICT,
    CONSTRAINT fk_rep_action_actor FOREIGN KEY (actor_user_id)
        REFERENCES users (user_id),
    CONSTRAINT ck_rep_action_type
        CHECK (action_type IN ('REQUEST', 'APPROVE', 'REJECT', 'REVOKE')),
    CONSTRAINT ck_rep_action_previous
        CHECK (previous_status IS NULL OR previous_status IN ('PENDING', 'ACTIVE', 'REJECTED', 'REVOKED')),
    CONSTRAINT ck_rep_action_new
        CHECK (new_status IN ('PENDING', 'ACTIVE', 'REJECTED', 'REVOKED'))
);

CREATE INDEX IF NOT EXISTS ix_rep_action_assignment_time
    ON representative_assignment_actions (assignment_id, action_at);
CREATE INDEX IF NOT EXISTS ix_rep_action_actor
    ON representative_assignment_actions (actor_user_id);

COMMIT;
