-- SAPLE MIGRATION 002 - JOB POSTINGS AND APPLICATIONS
-- Additive and non-destructive. Run after 001.
--
-- What it does:
--   1. Adds JOB_POSTINGS owned by one company and created by a representative.
--   2. Adds JOB_APPLICATIONS with one application per applicant and job.
--   3. Adds JOB_APPLICATION_STATUS_HISTORY, the immutable decision trail.
--
-- Deliberately omitted: resume file references. Saple does not accept raw
-- document uploads and never fetches applicant-supplied URLs.

BEGIN;

-- ================================================================
-- 1. JOB POSTINGS
-- ================================================================

CREATE TABLE IF NOT EXISTS job_postings (
    job_id               BIGINT GENERATED BY DEFAULT AS IDENTITY,
    company_id           BIGINT NOT NULL,
    created_by_user_id   BIGINT NOT NULL,
    created_by_assignment_id BIGINT,
    role_id              BIGINT,
    title                VARCHAR(160) NOT NULL,
    description          TEXT NOT NULL,
    requirements         TEXT,
    location             VARCHAR(120) NOT NULL,
    employment_type      VARCHAR(15) NOT NULL,
    work_mode            VARCHAR(10) NOT NULL,
    salary_min           NUMERIC(12,2),
    salary_max           NUMERIC(12,2),
    salary_currency      VARCHAR(3),
    salary_period        VARCHAR(10),
    application_deadline DATE NOT NULL,
    job_status           VARCHAR(10) DEFAULT 'DRAFT' NOT NULL,
    published_at         TIMESTAMPTZ,
    closed_at            TIMESTAMPTZ,
    created_at           TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at           TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_job_postings PRIMARY KEY (job_id),
    CONSTRAINT fk_job_company FOREIGN KEY (company_id)
        REFERENCES companies (company_id) ON DELETE RESTRICT,
    CONSTRAINT fk_job_creator FOREIGN KEY (created_by_user_id)
        REFERENCES users (user_id),
    CONSTRAINT fk_job_assignment FOREIGN KEY (created_by_assignment_id)
        REFERENCES company_representatives (assignment_id) ON DELETE SET NULL,
    CONSTRAINT fk_job_role FOREIGN KEY (role_id)
        REFERENCES job_roles (role_id),
    CONSTRAINT ck_job_title CHECK (TRIM(title) <> ''),
    CONSTRAINT ck_job_description CHECK (LENGTH(TRIM(description)) >= 20),
    CONSTRAINT ck_job_location CHECK (TRIM(location) <> ''),
    CONSTRAINT ck_job_employment_type
        CHECK (employment_type IN ('FULL_TIME', 'PART_TIME', 'CONTRACT', 'INTERN')),
    CONSTRAINT ck_job_work_mode CHECK (work_mode IN ('ONSITE', 'HYBRID', 'REMOTE')),
    CONSTRAINT ck_job_status CHECK (job_status IN ('DRAFT', 'PUBLISHED', 'CLOSED', 'ARCHIVED')),
    -- Salary is optional, but a partial or inverted range is never stored.
    CONSTRAINT ck_job_salary_range CHECK (
        (salary_min IS NULL AND salary_max IS NULL AND salary_currency IS NULL AND salary_period IS NULL)
        OR
        (salary_min IS NOT NULL AND salary_max IS NOT NULL
            AND salary_currency IS NOT NULL AND salary_period IS NOT NULL
            AND salary_min > 0 AND salary_max >= salary_min
            AND salary_max <= 9999999999.99)
    ),
    CONSTRAINT ck_job_salary_currency CHECK (
        salary_currency IS NULL
        OR (LENGTH(salary_currency) = 3 AND salary_currency = UPPER(salary_currency))
    ),
    CONSTRAINT ck_job_salary_period CHECK (
        salary_period IS NULL OR salary_period IN ('MONTHLY', 'YEARLY')
    ),
    -- Publication timestamps must match the lifecycle state.
    CONSTRAINT ck_job_published_at CHECK (
        (job_status = 'DRAFT' AND published_at IS NULL)
        OR
        (job_status <> 'DRAFT' AND published_at IS NOT NULL)
    ),
    CONSTRAINT ck_job_closed_at CHECK (
        (job_status IN ('CLOSED', 'ARCHIVED') AND closed_at IS NOT NULL)
        OR
        (job_status IN ('DRAFT', 'PUBLISHED') AND closed_at IS NULL)
    )
);

CREATE INDEX IF NOT EXISTS ix_job_company_status
    ON job_postings (company_id, job_status);
CREATE INDEX IF NOT EXISTS ix_job_status_deadline
    ON job_postings (job_status, application_deadline);
CREATE INDEX IF NOT EXISTS ix_job_role ON job_postings (role_id);
CREATE INDEX IF NOT EXISTS ix_job_creator ON job_postings (created_by_user_id);
CREATE INDEX IF NOT EXISTS ix_job_assignment ON job_postings (created_by_assignment_id);
CREATE INDEX IF NOT EXISTS ix_job_published_at ON job_postings (published_at DESC);

-- ================================================================
-- 2. JOB APPLICATIONS
-- ================================================================

CREATE TABLE IF NOT EXISTS job_applications (
    application_id     BIGINT GENERATED BY DEFAULT AS IDENTITY,
    job_id             BIGINT NOT NULL,
    applicant_user_id  BIGINT NOT NULL,
    cover_letter       TEXT NOT NULL,
    application_status VARCHAR(15) DEFAULT 'SUBMITTED' NOT NULL,
    submitted_at       TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at         TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    reviewed_by        BIGINT,
    reviewed_at        TIMESTAMPTZ,
    CONSTRAINT pk_job_applications PRIMARY KEY (application_id),
    CONSTRAINT uk_job_applications_once UNIQUE (job_id, applicant_user_id),
    CONSTRAINT fk_application_job FOREIGN KEY (job_id)
        REFERENCES job_postings (job_id) ON DELETE RESTRICT,
    CONSTRAINT fk_application_applicant FOREIGN KEY (applicant_user_id)
        REFERENCES users (user_id),
    CONSTRAINT fk_application_reviewer FOREIGN KEY (reviewed_by)
        REFERENCES users (user_id),
    CONSTRAINT ck_application_cover_letter
        CHECK (LENGTH(TRIM(cover_letter)) BETWEEN 30 AND 4000),
    CONSTRAINT ck_application_status CHECK (application_status IN (
        'SUBMITTED', 'UNDER_REVIEW', 'SHORTLISTED', 'REJECTED', 'WITHDRAWN', 'ACCEPTED'
    )),
    -- A reviewed application always records who reviewed it and when.
    CONSTRAINT ck_application_review CHECK (
        (application_status IN ('SUBMITTED', 'WITHDRAWN') AND reviewed_by IS NULL AND reviewed_at IS NULL)
        OR
        (application_status IN ('UNDER_REVIEW', 'SHORTLISTED', 'REJECTED', 'ACCEPTED')
            AND reviewed_by IS NOT NULL AND reviewed_at IS NOT NULL)
    )
);

CREATE INDEX IF NOT EXISTS ix_application_job_status
    ON job_applications (job_id, application_status);
CREATE INDEX IF NOT EXISTS ix_application_applicant
    ON job_applications (applicant_user_id, submitted_at DESC);
CREATE INDEX IF NOT EXISTS ix_application_reviewer ON job_applications (reviewed_by);

-- ================================================================
-- 3. IMMUTABLE APPLICATION STATUS HISTORY
-- ================================================================

CREATE TABLE IF NOT EXISTS job_application_status_history (
    history_id      BIGINT GENERATED BY DEFAULT AS IDENTITY,
    application_id  BIGINT NOT NULL,
    actor_user_id   BIGINT NOT NULL,
    previous_status VARCHAR(15),
    new_status      VARCHAR(15) NOT NULL,
    action_note     VARCHAR(1000),
    action_at       TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_job_application_status_history PRIMARY KEY (history_id),
    CONSTRAINT fk_application_history_application FOREIGN KEY (application_id)
        REFERENCES job_applications (application_id) ON DELETE RESTRICT,
    CONSTRAINT fk_application_history_actor FOREIGN KEY (actor_user_id)
        REFERENCES users (user_id),
    CONSTRAINT ck_application_history_previous CHECK (
        previous_status IS NULL OR previous_status IN (
            'SUBMITTED', 'UNDER_REVIEW', 'SHORTLISTED', 'REJECTED', 'WITHDRAWN', 'ACCEPTED'
        )
    ),
    CONSTRAINT ck_application_history_new CHECK (new_status IN (
        'SUBMITTED', 'UNDER_REVIEW', 'SHORTLISTED', 'REJECTED', 'WITHDRAWN', 'ACCEPTED'
    ))
);

CREATE INDEX IF NOT EXISTS ix_application_history_application
    ON job_application_status_history (application_id, action_at);
CREATE INDEX IF NOT EXISTS ix_application_history_actor
    ON job_application_status_history (actor_user_id);

COMMIT;
