-- SAPLE MIGRATION 003 - ANNOUNCEMENTS AND PRIVATE NOTIFICATIONS
-- Additive and non-destructive. Run after 002.
--
-- ANNOUNCEMENTS are public, admin-managed and plain text only.
-- NOTIFICATIONS are private and always scoped to exactly one account.

BEGIN;

-- ================================================================
-- 1. PUBLIC SITE ANNOUNCEMENTS
-- ================================================================

CREATE TABLE IF NOT EXISTS announcements (
    announcement_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    title           VARCHAR(160) NOT NULL,
    message         VARCHAR(600) NOT NULL,
    severity        VARCHAR(10) DEFAULT 'INFO' NOT NULL,
    is_dismissible  BOOLEAN DEFAULT TRUE NOT NULL,
    is_active       BOOLEAN DEFAULT TRUE NOT NULL,
    starts_at       TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ends_at         TIMESTAMPTZ,
    created_by      BIGINT NOT NULL,
    created_at      TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at      TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_announcements PRIMARY KEY (announcement_id),
    CONSTRAINT fk_announcements_author FOREIGN KEY (created_by)
        REFERENCES users (user_id),
    CONSTRAINT ck_announcements_title CHECK (TRIM(title) <> ''),
    CONSTRAINT ck_announcements_message CHECK (TRIM(message) <> ''),
    CONSTRAINT ck_announcements_severity CHECK (severity IN ('INFO', 'WARNING', 'CRITICAL')),
    CONSTRAINT ck_announcements_window CHECK (ends_at IS NULL OR ends_at > starts_at),
    -- Announcement text is rendered as plain text; markup is rejected at rest too.
    CONSTRAINT ck_announcements_plain_text CHECK (
        title !~ '[<>]' AND message !~ '[<>]'
    )
);

CREATE INDEX IF NOT EXISTS ix_announcements_window
    ON announcements (is_active, starts_at, ends_at);
CREATE INDEX IF NOT EXISTS ix_announcements_author ON announcements (created_by);

-- ================================================================
-- 2. PRIVATE PER-ACCOUNT NOTIFICATIONS
-- ================================================================

CREATE TABLE IF NOT EXISTS notifications (
    notification_id     BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id             BIGINT NOT NULL,
    notification_type   VARCHAR(30) NOT NULL,
    title               VARCHAR(160) NOT NULL,
    message             VARCHAR(600) NOT NULL,
    related_entity_type VARCHAR(30),
    related_entity_id   BIGINT,
    read_at             TIMESTAMPTZ,
    created_at          TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_notifications PRIMARY KEY (notification_id),
    CONSTRAINT fk_notifications_user FOREIGN KEY (user_id)
        REFERENCES users (user_id) ON DELETE CASCADE,
    CONSTRAINT ck_notifications_title CHECK (TRIM(title) <> ''),
    CONSTRAINT ck_notifications_message CHECK (TRIM(message) <> ''),
    CONSTRAINT ck_notifications_type CHECK (notification_type IN (
        'VERIFICATION_DECISION',
        'SUBMISSION_DECISION',
        'REPRESENTATIVE_DECISION',
        'REPORT_OUTCOME',
        'APPLICATION_RECEIVED',
        'APPLICATION_STATUS',
        'JOB_CLOSED',
        'SECURITY_EVENT'
    )),
    CONSTRAINT ck_notifications_entity CHECK (
        (related_entity_type IS NULL AND related_entity_id IS NULL)
        OR
        (related_entity_type IN (
            'SUBMISSION', 'VERIFICATION', 'JOB', 'APPLICATION', 'ASSIGNMENT', 'REPORT', 'ACCOUNT'
        ) AND related_entity_id IS NOT NULL AND related_entity_id > 0)
    ),
    -- Notification text is rendered as plain text; markup is rejected at rest too.
    CONSTRAINT ck_notifications_plain_text CHECK (
        title !~ '[<>]' AND message !~ '[<>]'
    )
);

CREATE INDEX IF NOT EXISTS ix_notifications_owner_time
    ON notifications (user_id, created_at DESC, notification_id DESC);
CREATE INDEX IF NOT EXISTS ix_notifications_unread
    ON notifications (user_id)
    WHERE read_at IS NULL;

COMMIT;
