BEGIN;
CREATE TABLE IF NOT EXISTS direct_messages (
    message_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    sender_user_id BIGINT NOT NULL,
    recipient_user_id BIGINT NOT NULL,
    message_body VARCHAR(2000),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    edited_at TIMESTAMPTZ,
    deleted_at TIMESTAMPTZ,
    read_at TIMESTAMPTZ,
    CONSTRAINT pk_direct_messages PRIMARY KEY (message_id),
    CONSTRAINT fk_direct_messages_sender FOREIGN KEY (sender_user_id)
        REFERENCES users (user_id) ON DELETE CASCADE,
    CONSTRAINT fk_direct_messages_recipient FOREIGN KEY (recipient_user_id)
        REFERENCES users (user_id) ON DELETE CASCADE,
    CONSTRAINT ck_direct_messages_distinct_users CHECK (sender_user_id <> recipient_user_id),
    CONSTRAINT ck_direct_messages_live_body CHECK (deleted_at IS NOT NULL OR (message_body IS NOT NULL AND LENGTH(TRIM(message_body)) > 0))
);
CREATE INDEX IF NOT EXISTS ix_direct_messages_sender_recipient ON direct_messages (sender_user_id, recipient_user_id, message_id DESC);
CREATE INDEX IF NOT EXISTS ix_direct_messages_recipient_sender ON direct_messages (recipient_user_id, sender_user_id, message_id DESC);
CREATE INDEX IF NOT EXISTS ix_direct_messages_unread ON direct_messages (recipient_user_id, read_at, message_id DESC);
COMMIT;
