BEGIN;

ALTER TABLE users ADD COLUMN IF NOT EXISTS headline VARCHAR(160);
ALTER TABLE users ADD COLUMN IF NOT EXISTS bio VARCHAR(2000);

CREATE TABLE IF NOT EXISTS user_education (
    education_id       BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id            BIGINT NOT NULL,
    institution        VARCHAR(180) NOT NULL,
    degree             VARCHAR(160) NOT NULL,
    field_of_study     VARCHAR(160) NOT NULL,
    start_date         DATE NOT NULL,
    end_date           DATE,
    currently_studying BOOLEAN DEFAULT FALSE NOT NULL,
    description        VARCHAR(2000),
    CONSTRAINT pk_user_education PRIMARY KEY (education_id),
    CONSTRAINT fk_user_education_user FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE,
    CONSTRAINT ck_user_education_institution CHECK (TRIM(institution) <> ''),
    CONSTRAINT ck_user_education_degree CHECK (TRIM(degree) <> ''),
    CONSTRAINT ck_user_education_field CHECK (TRIM(field_of_study) <> ''),
    CONSTRAINT ck_user_education_dates CHECK (
        (currently_studying AND end_date IS NULL)
        OR (NOT currently_studying AND end_date IS NOT NULL AND end_date >= start_date)
    )
);
CREATE INDEX IF NOT EXISTS idx_user_education_user ON user_education (user_id, start_date DESC);

CREATE TABLE IF NOT EXISTS user_experience (
    experience_id      BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id            BIGINT NOT NULL,
    organization       VARCHAR(180) NOT NULL,
    job_title          VARCHAR(160) NOT NULL,
    employment_type    VARCHAR(60),
    location           VARCHAR(160),
    start_date         DATE NOT NULL,
    end_date           DATE,
    currently_working  BOOLEAN DEFAULT FALSE NOT NULL,
    description        VARCHAR(2000),
    CONSTRAINT pk_user_experience PRIMARY KEY (experience_id),
    CONSTRAINT fk_user_experience_user FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE,
    CONSTRAINT ck_user_experience_organization CHECK (TRIM(organization) <> ''),
    CONSTRAINT ck_user_experience_title CHECK (TRIM(job_title) <> ''),
    CONSTRAINT ck_user_experience_dates CHECK (
        (currently_working AND end_date IS NULL)
        OR (NOT currently_working AND end_date IS NOT NULL AND end_date >= start_date)
    )
);
CREATE INDEX IF NOT EXISTS idx_user_experience_user ON user_experience (user_id, start_date DESC);

CREATE TABLE IF NOT EXISTS skills (
    skill_id   BIGINT GENERATED BY DEFAULT AS IDENTITY,
    skill_name VARCHAR(80) NOT NULL,
    CONSTRAINT pk_skills PRIMARY KEY (skill_id),
    CONSTRAINT ck_skills_name CHECK (TRIM(skill_name) <> '')
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_skills_name_ci ON skills (LOWER(skill_name));

CREATE TABLE IF NOT EXISTS user_skills (
    user_id  BIGINT NOT NULL,
    skill_id BIGINT NOT NULL,
    CONSTRAINT pk_user_skills PRIMARY KEY (user_id, skill_id),
    CONSTRAINT fk_user_skills_user FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE,
    CONSTRAINT fk_user_skills_skill FOREIGN KEY (skill_id) REFERENCES skills (skill_id) ON DELETE RESTRICT
);

COMMIT;
