-- Migration 009: Premium subscriptions, one-day trial, promo codes,
-- premium jobs, profile views and Premium AI usage.
--
-- Additive only: new tables, one new job_postings column (existing jobs
-- become FREE), two new notification types, and the public jobs view gains
-- the access_level column at its end. No existing row is changed or removed.
-- Re-running this file is harmless.

BEGIN;

-- PREMIUM_PLANS is the server-side price list. Checkout always reads the
-- price from here; a price sent by a browser is never used.
CREATE TABLE IF NOT EXISTS premium_plans (
    plan_id       BIGINT GENERATED BY DEFAULT AS IDENTITY,
    plan_code     VARCHAR(30) NOT NULL,
    name          VARCHAR(80) NOT NULL,
    duration_days INTEGER NOT NULL,
    price_bdt     NUMERIC(10,2) NOT NULL,
    is_active     BOOLEAN DEFAULT TRUE NOT NULL,
    sort_order    INTEGER DEFAULT 0 NOT NULL,
    created_at    TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at    TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_premium_plans PRIMARY KEY (plan_id),
    CONSTRAINT uk_premium_plans_code UNIQUE (plan_code),
    CONSTRAINT ck_premium_plans_code CHECK (plan_code ~ '^[A-Z0-9_]{2,30}$'),
    CONSTRAINT ck_premium_plans_name CHECK (TRIM(name) <> ''),
    CONSTRAINT ck_premium_plans_duration CHECK (duration_days > 0),
    CONSTRAINT ck_premium_plans_price CHECK (price_bdt >= 0)
);

-- PREMIUM_TRIAL_CLAIMS keeps permanent proof of the one free trial. The
-- primary key on user_id is the hard guarantee: a second row for the same
-- account cannot exist, however many requests arrive at once.
CREATE TABLE IF NOT EXISTS premium_trial_claims (
    user_id    BIGINT NOT NULL,
    claimed_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    starts_at  TIMESTAMPTZ NOT NULL,
    ends_at    TIMESTAMPTZ NOT NULL,
    CONSTRAINT pk_premium_trial_claims PRIMARY KEY (user_id),
    CONSTRAINT fk_premium_trial_user FOREIGN KEY (user_id)
        REFERENCES users (user_id),
    CONSTRAINT ck_premium_trial_period CHECK (ends_at > starts_at)
);

-- PREMIUM_PROMO_CODES are admin-managed discount (promo or referral) codes.
CREATE TABLE IF NOT EXISTS premium_promo_codes (
    promo_code_id        BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code                 VARCHAR(40) NOT NULL,
    description          VARCHAR(300),
    discount_type        VARCHAR(10) NOT NULL,
    discount_value       NUMERIC(10,2) NOT NULL,
    max_discount_bdt     NUMERIC(10,2),
    applicable_plan_code VARCHAR(30),
    max_redemptions      INTEGER,
    per_user_limit       INTEGER DEFAULT 1 NOT NULL,
    valid_from           TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    valid_until          TIMESTAMPTZ,
    is_active            BOOLEAN DEFAULT TRUE NOT NULL,
    created_by           BIGINT,
    created_at           TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at           TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_premium_promo_codes PRIMARY KEY (promo_code_id),
    CONSTRAINT uk_premium_promo_code UNIQUE (code),
    CONSTRAINT fk_premium_promo_plan FOREIGN KEY (applicable_plan_code)
        REFERENCES premium_plans (plan_code),
    CONSTRAINT fk_premium_promo_creator FOREIGN KEY (created_by)
        REFERENCES users (user_id),
    CONSTRAINT ck_premium_promo_code CHECK (code ~ '^[A-Z0-9_-]{3,40}$'),
    CONSTRAINT ck_premium_promo_type CHECK (discount_type IN ('PERCENT', 'FIXED')),
    CONSTRAINT ck_premium_promo_value CHECK (
        discount_value > 0 AND (discount_type <> 'PERCENT' OR discount_value <= 100)
    ),
    CONSTRAINT ck_premium_promo_max_discount CHECK (max_discount_bdt IS NULL OR max_discount_bdt > 0),
    CONSTRAINT ck_premium_promo_max_redemptions CHECK (max_redemptions IS NULL OR max_redemptions > 0),
    CONSTRAINT ck_premium_promo_per_user CHECK (per_user_limit > 0),
    CONSTRAINT ck_premium_promo_window CHECK (valid_until IS NULL OR valid_until > valid_from)
);

-- PREMIUM_PAYMENTS records every checkout attempt. It is created before the
-- gateway is contacted, and only verified settlement marks it SUCCEEDED.
CREATE TABLE IF NOT EXISTS premium_payments (
    payment_id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
    public_id              UUID DEFAULT gen_random_uuid() NOT NULL,
    user_id                BIGINT NOT NULL,
    plan_id                BIGINT NOT NULL,
    promo_code_id          BIGINT,
    base_amount_bdt        NUMERIC(10,2) NOT NULL,
    discount_amount_bdt    NUMERIC(10,2) DEFAULT 0 NOT NULL,
    final_amount_bdt       NUMERIC(10,2) NOT NULL,
    currency               VARCHAR(3) DEFAULT 'BDT' NOT NULL,
    gateway                VARCHAR(30) DEFAULT 'SSLCOMMERZ' NOT NULL,
    gateway_session_key    VARCHAR(255),
    gateway_transaction_id VARCHAR(255),
    gateway_validation_id  VARCHAR(255),
    status                 VARCHAR(10) DEFAULT 'INITIATED' NOT NULL,
    initiated_at           TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    completed_at           TIMESTAMPTZ,
    created_at             TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at             TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_premium_payments PRIMARY KEY (payment_id),
    CONSTRAINT uk_premium_payments_public UNIQUE (public_id),
    CONSTRAINT fk_premium_payment_user FOREIGN KEY (user_id)
        REFERENCES users (user_id),
    CONSTRAINT fk_premium_payment_plan FOREIGN KEY (plan_id)
        REFERENCES premium_plans (plan_id),
    CONSTRAINT fk_premium_payment_promo FOREIGN KEY (promo_code_id)
        REFERENCES premium_promo_codes (promo_code_id),
    CONSTRAINT ck_premium_payment_amounts CHECK (
        base_amount_bdt >= 0 AND discount_amount_bdt >= 0 AND final_amount_bdt >= 0
        AND final_amount_bdt = base_amount_bdt - discount_amount_bdt
    ),
    CONSTRAINT ck_premium_payment_currency CHECK (currency = 'BDT'),
    CONSTRAINT ck_premium_payment_status CHECK (
        status IN ('INITIATED', 'PENDING', 'SUCCEEDED', 'FAILED', 'CANCELLED', 'REFUNDED')
    ),
    CONSTRAINT ck_premium_payment_completion CHECK (
        (status IN ('INITIATED', 'PENDING') AND completed_at IS NULL)
        OR (status NOT IN ('INITIATED', 'PENDING') AND completed_at IS NOT NULL)
    )
);

-- PREMIUM_ACCESS_PERIODS holds paid access. Each verified payment grants
-- exactly one period (the unique payment_id), so a repeated callback can
-- never add time twice. Premium is never stored as a flag on users.
CREATE TABLE IF NOT EXISTS premium_access_periods (
    access_id   BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id     BIGINT NOT NULL,
    source_type VARCHAR(10) DEFAULT 'PAID' NOT NULL,
    plan_id     BIGINT NOT NULL,
    payment_id  BIGINT NOT NULL,
    starts_at   TIMESTAMPTZ NOT NULL,
    ends_at     TIMESTAMPTZ NOT NULL,
    created_at  TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_premium_access_periods PRIMARY KEY (access_id),
    CONSTRAINT uk_premium_access_payment UNIQUE (payment_id),
    CONSTRAINT fk_premium_access_user FOREIGN KEY (user_id)
        REFERENCES users (user_id),
    CONSTRAINT fk_premium_access_plan FOREIGN KEY (plan_id)
        REFERENCES premium_plans (plan_id),
    CONSTRAINT fk_premium_access_payment FOREIGN KEY (payment_id)
        REFERENCES premium_payments (payment_id),
    CONSTRAINT ck_premium_access_source CHECK (source_type = 'PAID'),
    CONSTRAINT ck_premium_access_period CHECK (ends_at > starts_at)
);

-- PREMIUM_PROMO_REDEMPTIONS tracks each code use: reserved at checkout,
-- redeemed on verified payment, released on failure or expiry.
CREATE TABLE IF NOT EXISTS premium_promo_redemptions (
    redemption_id       BIGINT GENERATED BY DEFAULT AS IDENTITY,
    promo_code_id       BIGINT NOT NULL,
    user_id             BIGINT NOT NULL,
    payment_id          BIGINT NOT NULL,
    discount_amount_bdt NUMERIC(10,2) NOT NULL,
    status              VARCHAR(10) DEFAULT 'RESERVED' NOT NULL,
    reserved_at         TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    redeemed_at         TIMESTAMPTZ,
    released_at         TIMESTAMPTZ,
    CONSTRAINT pk_premium_promo_redemptions PRIMARY KEY (redemption_id),
    CONSTRAINT uk_premium_redemption_payment UNIQUE (payment_id),
    CONSTRAINT fk_premium_redemption_code FOREIGN KEY (promo_code_id)
        REFERENCES premium_promo_codes (promo_code_id),
    CONSTRAINT fk_premium_redemption_user FOREIGN KEY (user_id)
        REFERENCES users (user_id),
    CONSTRAINT fk_premium_redemption_payment FOREIGN KEY (payment_id)
        REFERENCES premium_payments (payment_id),
    CONSTRAINT ck_premium_redemption_discount CHECK (discount_amount_bdt >= 0),
    CONSTRAINT ck_premium_redemption_status CHECK (status IN ('RESERVED', 'REDEEMED', 'RELEASED')),
    CONSTRAINT ck_premium_redemption_state CHECK (
        (status = 'RESERVED' AND redeemed_at IS NULL AND released_at IS NULL)
        OR (status = 'REDEEMED' AND redeemed_at IS NOT NULL AND released_at IS NULL)
        OR (status = 'RELEASED' AND released_at IS NOT NULL AND redeemed_at IS NULL)
    )
);

-- PROFILE_VIEWS aggregates signed-in, non-self profile views per day.
-- Anonymous visitors are never recorded.
CREATE TABLE IF NOT EXISTS profile_views (
    profile_user_id BIGINT NOT NULL,
    viewer_user_id  BIGINT NOT NULL,
    view_date       DATE DEFAULT CURRENT_DATE NOT NULL,
    first_viewed_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    last_viewed_at  TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    view_count      INTEGER DEFAULT 1 NOT NULL,
    CONSTRAINT pk_profile_views PRIMARY KEY (profile_user_id, viewer_user_id, view_date),
    CONSTRAINT fk_profile_views_profile FOREIGN KEY (profile_user_id)
        REFERENCES users (user_id) ON DELETE CASCADE,
    CONSTRAINT fk_profile_views_viewer FOREIGN KEY (viewer_user_id)
        REFERENCES users (user_id) ON DELETE CASCADE,
    CONSTRAINT ck_profile_views_not_self CHECK (profile_user_id <> viewer_user_id),
    CONSTRAINT ck_profile_views_count CHECK (view_count > 0),
    CONSTRAINT ck_profile_views_order CHECK (last_viewed_at >= first_viewed_at)
);

-- PREMIUM_AI_USAGE counts Premium AI requests for daily limits. It stores
-- no prompt or resume text.
CREATE TABLE IF NOT EXISTS premium_ai_usage (
    usage_id      BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id       BIGINT NOT NULL,
    feature_type  VARCHAR(20) NOT NULL,
    model         VARCHAR(120),
    input_tokens  INTEGER,
    output_tokens INTEGER,
    created_at    TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_premium_ai_usage PRIMARY KEY (usage_id),
    CONSTRAINT fk_premium_ai_usage_user FOREIGN KEY (user_id)
        REFERENCES users (user_id) ON DELETE CASCADE,
    CONSTRAINT ck_premium_ai_feature CHECK (feature_type IN ('ADVANCED_CHAT', 'RESUME_GENERATION')),
    CONSTRAINT ck_premium_ai_tokens CHECK (
        (input_tokens IS NULL OR input_tokens >= 0) AND (output_tokens IS NULL OR output_tokens >= 0)
    )
);

CREATE INDEX IF NOT EXISTS ix_premium_payments_user ON premium_payments (user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS ix_premium_payments_status ON premium_payments (status, created_at DESC);
CREATE INDEX IF NOT EXISTS ix_premium_access_user_end ON premium_access_periods (user_id, ends_at DESC);
CREATE INDEX IF NOT EXISTS ix_premium_redemptions_code ON premium_promo_redemptions (promo_code_id, status);
CREATE INDEX IF NOT EXISTS ix_premium_redemptions_user ON premium_promo_redemptions (promo_code_id, user_id, status);
CREATE INDEX IF NOT EXISTS ix_profile_views_profile ON profile_views (profile_user_id, last_viewed_at DESC);
CREATE INDEX IF NOT EXISTS ix_premium_ai_usage_user ON premium_ai_usage (user_id, feature_type, created_at DESC);

-- The two plans. Prices are authoritative here, in BDT.
INSERT INTO premium_plans (plan_code, name, duration_days, price_bdt, sort_order) VALUES
    ('PREMIUM_1M', 'Premium 1 Month', 30, 120.00, 1),
    ('PREMIUM_3M', 'Premium 3 Months', 90, 300.00, 2)
ON CONFLICT (plan_code) DO NOTHING;

-- Existing vacancies stay FREE; only a representative or the optional demo
-- script ever marks a job PREMIUM.
ALTER TABLE job_postings
    ADD COLUMN IF NOT EXISTS access_level VARCHAR(10) DEFAULT 'FREE' NOT NULL
    CONSTRAINT ck_job_access_level CHECK (access_level IN ('FREE', 'PREMIUM'));

CREATE INDEX IF NOT EXISTS ix_job_postings_access ON job_postings (access_level);

-- Two new notification types for the trial and for a purchase.
ALTER TABLE notifications DROP CONSTRAINT IF EXISTS ck_notifications_type;
ALTER TABLE notifications ADD CONSTRAINT ck_notifications_type CHECK (notification_type IN (
    'VERIFICATION_DECISION',
    'SUBMISSION_DECISION',
    'REPRESENTATIVE_DECISION',
    'REPORT_OUTCOME',
    'APPLICATION_RECEIVED',
    'APPLICATION_STATUS',
    'JOB_CLOSED',
    'SECURITY_EVENT',
    'PREMIUM_TRIAL_STARTED',
    'PREMIUM_PURCHASE'
));

-- The public jobs view carries access_level so the API can show a locked
-- teaser for Premium vacancies. New column appended at the end.
CREATE OR REPLACE VIEW vw_public_open_jobs AS
SELECT jp.job_id,
       jp.company_id,
       c.company_name,
       c.industry,
       jp.role_id,
       jr.role_name,
       jr.role_category,
       jp.title,
       jp.description,
       jp.requirements,
       jp.location,
       jp.employment_type,
       jp.work_mode,
       jp.salary_min,
       jp.salary_max,
       jp.salary_currency,
       jp.salary_period,
       jp.application_deadline,
       jp.published_at,
       jp.access_level
FROM job_postings jp
JOIN companies c ON c.company_id = jp.company_id
LEFT JOIN job_roles jr ON jr.role_id = jp.role_id
WHERE jp.job_status = 'PUBLISHED'
  AND jp.application_deadline >= CURRENT_DATE;

-- Supabase browser roles get no direct access to the new tables either.
DO $saple_security$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN
        REVOKE ALL ON ALL TABLES IN SCHEMA public FROM anon;
        REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM anon;
    END IF;
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN
        REVOKE ALL ON ALL TABLES IN SCHEMA public FROM authenticated;
        REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM authenticated;
    END IF;
END
$saple_security$;

COMMIT;
