-- ML-assisted moderation. Human decisions remain final. Existing submissions
-- and public views stay unchanged until the application enables screening.
-- Run only after 010_job_application_resumes.sql; never apply automatically.
BEGIN;

CREATE TABLE IF NOT EXISTS ml_model_registry (
    model_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    model_key VARCHAR(160) NOT NULL,
    content_type VARCHAR(16) NOT NULL,
    scope_key VARCHAR(160),
    model_version VARCHAR(80) NOT NULL,
    artifact_uri TEXT NOT NULL,
    artifact_sha256 CHAR(64) NOT NULL,
    feature_schema_version VARCHAR(80) NOT NULL,
    training_dataset_fingerprint CHAR(64) NOT NULL,
    trained_at TIMESTAMPTZ NOT NULL,
    training_sample_count INTEGER NOT NULL,
    approved_sample_count INTEGER NOT NULL,
    rejected_sample_count INTEGER NOT NULL,
    metrics JSONB NOT NULL DEFAULT '{}'::jsonb,
    auto_publish_threshold NUMERIC(6,5),
    ood_threshold NUMERIC,
    status VARCHAR(12) NOT NULL DEFAULT 'CANDIDATE',
    activated_at TIMESTAMPTZ,
    retired_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_ml_model_registry PRIMARY KEY (model_id),
    CONSTRAINT uq_ml_model_registry_version UNIQUE (model_key, model_version),
    CONSTRAINT ck_ml_model_registry_type CHECK (content_type IN ('SALARY','REVIEW','INTERVIEW','JOB','PROFILE','COMPANY')),
    CONSTRAINT ck_ml_model_registry_status CHECK (status IN ('CANDIDATE','ACTIVE','RETIRED','DISABLED')),
    CONSTRAINT ck_ml_model_registry_sha CHECK (artifact_sha256 ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_ml_model_registry_fingerprint CHECK (training_dataset_fingerprint ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_ml_model_registry_counts CHECK (training_sample_count >= 0 AND approved_sample_count >= 0 AND rejected_sample_count >= 0),
    CONSTRAINT ck_ml_model_registry_threshold CHECK (auto_publish_threshold IS NULL OR auto_publish_threshold BETWEEN 0 AND 1)
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_ml_model_registry_active
    ON ml_model_registry (model_key) WHERE status = 'ACTIVE';

CREATE TABLE IF NOT EXISTS content_screenings (
    screening_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    entity_type VARCHAR(16) NOT NULL,
    entity_id BIGINT NOT NULL,
    revision_no INTEGER NOT NULL DEFAULT 1,
    submitted_by_user_id BIGINT,
    model_key VARCHAR(160),
    model_version VARCHAR(80),
    feature_schema_version VARCHAR(80),
    screening_status VARCHAR(16) NOT NULL,
    risk_probability NUMERIC(6,5),
    safe_probability NUMERIC(6,5),
    confidence NUMERIC(6,5),
    reason_codes JSONB NOT NULL DEFAULT '[]'::jsonb,
    model_metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    publication_state VARCHAR(12) NOT NULL DEFAULT 'HELD',
    manual_review_status VARCHAR(10) NOT NULL DEFAULT 'PENDING',
    screened_at TIMESTAMPTZ,
    provisional_published_at TIMESTAMPTZ,
    human_review_due_at TIMESTAMPTZ,
    reviewed_at TIMESTAMPTZ,
    reviewed_by BIGINT,
    human_decision_note TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_content_screenings PRIMARY KEY (screening_id),
    CONSTRAINT uq_content_screenings_revision UNIQUE (entity_type, entity_id, revision_no),
    CONSTRAINT fk_content_screenings_submitter FOREIGN KEY (submitted_by_user_id) REFERENCES users (user_id),
    CONSTRAINT fk_content_screenings_reviewer FOREIGN KEY (reviewed_by) REFERENCES users (user_id),
    CONSTRAINT ck_content_screenings_type CHECK (entity_type IN ('SALARY','REVIEW','INTERVIEW','JOB','PROFILE','COMPANY')),
    CONSTRAINT ck_content_screenings_status CHECK (screening_status IN ('NOT_RUN','AUTO_PUBLISH','MANUAL_REVIEW','UNAVAILABLE','ERROR')),
    CONSTRAINT ck_content_screenings_publication CHECK (publication_state IN ('HELD','PROVISIONAL','CONFIRMED','REMOVED')),
    CONSTRAINT ck_content_screenings_manual CHECK (manual_review_status IN ('PENDING','APPROVED','REJECTED')),
    CONSTRAINT ck_content_screenings_revision CHECK (revision_no > 0),
    CONSTRAINT ck_content_screenings_risk CHECK (risk_probability IS NULL OR risk_probability BETWEEN 0 AND 1),
    CONSTRAINT ck_content_screenings_safe CHECK (safe_probability IS NULL OR safe_probability BETWEEN 0 AND 1),
    CONSTRAINT ck_content_screenings_confidence CHECK (confidence IS NULL OR confidence BETWEEN 0 AND 1),
    CONSTRAINT ck_content_screenings_reasons CHECK (jsonb_typeof(reason_codes) = 'array'),
    CONSTRAINT ck_content_screenings_metadata CHECK (jsonb_typeof(model_metadata) = 'object'),
    CONSTRAINT ck_content_screenings_provisional CHECK (publication_state <> 'PROVISIONAL' OR (screening_status = 'AUTO_PUBLISH' AND provisional_published_at IS NOT NULL))
);
CREATE INDEX IF NOT EXISTS ix_content_screenings_queue
    ON content_screenings (manual_review_status, publication_state, created_at);
CREATE INDEX IF NOT EXISTS ix_content_screenings_entity
    ON content_screenings (entity_type, entity_id, revision_no DESC);

CREATE TABLE IF NOT EXISTS professional_profile_revisions (
    revision_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    revision_no INTEGER NOT NULL,
    previous_public_snapshot JSONB NOT NULL,
    proposed_public_snapshot JSONB NOT NULL,
    applied_at TIMESTAMPTZ,
    screening_id BIGINT,
    review_status VARCHAR(10) NOT NULL DEFAULT 'PENDING',
    reviewed_at TIMESTAMPTZ,
    reviewed_by BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_professional_profile_revisions PRIMARY KEY (revision_id),
    CONSTRAINT uq_professional_profile_revisions_user_no UNIQUE (user_id, revision_no),
    CONSTRAINT fk_professional_profile_revisions_user FOREIGN KEY (user_id) REFERENCES users (user_id),
    CONSTRAINT fk_professional_profile_revisions_screening FOREIGN KEY (screening_id) REFERENCES content_screenings (screening_id),
    CONSTRAINT fk_professional_profile_revisions_reviewer FOREIGN KEY (reviewed_by) REFERENCES users (user_id),
    CONSTRAINT ck_professional_profile_revisions_review CHECK (review_status IN ('PENDING','APPROVED','REJECTED')),
    CONSTRAINT ck_professional_profile_revisions_previous CHECK (jsonb_typeof(previous_public_snapshot) = 'object'),
    CONSTRAINT ck_professional_profile_revisions_proposed CHECK (jsonb_typeof(proposed_public_snapshot) = 'object')
);

-- Central public visibility rule: a final human approval, or the latest
-- pending screening explicitly marked provisional. Existing rows remain
-- visible exactly as before; verified salary and rating aggregates still use
-- final APPROVED rows only.
CREATE OR REPLACE VIEW vw_public_visible_submissions AS
SELECT s.*,
       (s.submission_status = 'PENDING') AS awaiting_moderator_review
FROM submissions s
WHERE s.submission_status = 'APPROVED'
   OR (s.submission_status = 'PENDING' AND EXISTS (
       SELECT 1 FROM content_screenings cs
       WHERE cs.entity_type = s.submission_type AND cs.entity_id = s.submission_id
         AND cs.publication_state = 'PROVISIONAL'
         AND cs.revision_no = (SELECT MAX(latest.revision_no) FROM content_screenings latest
             WHERE latest.entity_type = cs.entity_type AND latest.entity_id = cs.entity_id)
   ));

-- Only final human labels from non-synthetic accounts are training inputs.
CREATE OR REPLACE VIEW vw_ml_human_reviewed_real_submissions AS
SELECT s.submission_id, s.user_id, s.company_id, s.submission_type,
       s.submission_status, s.verification_status, s.submitted_at, s.updated_at
FROM submissions s JOIN users u ON u.user_id = s.user_id
WHERE s.submission_status IN ('APPROVED','REJECTED')
  AND u.password_hash NOT LIKE '%SAPLE.BULK.DEMO.ACCOUNT.NO.LOGIN%'
  AND u.password_hash NOT LIKE '%DEMO_HASH_NOT_FOR_PRODUCTION%'
  AND u.email NOT LIKE '%@example.invalid'
  AND u.email NOT LIKE '%@example.test';

DO $saple_security$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN
        REVOKE ALL ON ml_model_registry, content_screenings, professional_profile_revisions FROM anon;
    END IF;
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN
        REVOKE ALL ON ml_model_registry, content_screenings, professional_profile_revisions FROM authenticated;
    END IF;
END
$saple_security$;
COMMIT;
