BEGIN;

ALTER TABLE users ADD COLUMN IF NOT EXISTS status_reason VARCHAR(1000);
ALTER TABLE users ADD COLUMN IF NOT EXISTS status_changed_at TIMESTAMPTZ;
ALTER TABLE users ADD COLUMN IF NOT EXISTS status_changed_by BIGINT REFERENCES users(user_id);
ALTER TABLE premium_trial_claims ADD COLUMN IF NOT EXISTS revoked_at TIMESTAMPTZ;
ALTER TABLE premium_trial_claims ADD COLUMN IF NOT EXISTS revoked_by BIGINT REFERENCES users(user_id);

CREATE TABLE IF NOT EXISTS admin_actions (
    action_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_user_id BIGINT NOT NULL REFERENCES users(user_id),
    action_type VARCHAR(40) NOT NULL,
    target_type VARCHAR(30) NOT NULL,
    target_id BIGINT NOT NULL,
    before_state JSONB NOT NULL DEFAULT '{}'::jsonb,
    after_state JSONB NOT NULL DEFAULT '{}'::jsonb,
    reason VARCHAR(1000) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_admin_action_reason CHECK (length(btrim(reason)) > 0)
);
CREATE INDEX IF NOT EXISTS ix_admin_actions_target ON admin_actions(target_type, target_id, created_at DESC);

-- Payment records stay immutable. Manual access uses a period with no payment.
ALTER TABLE premium_access_periods ALTER COLUMN source_type TYPE VARCHAR(20);
ALTER TABLE premium_access_periods ALTER COLUMN payment_id DROP NOT NULL;
ALTER TABLE premium_access_periods DROP CONSTRAINT IF EXISTS ck_premium_access_source;
ALTER TABLE premium_access_periods ADD CONSTRAINT ck_premium_access_source
  CHECK ((source_type = 'PAID' AND payment_id IS NOT NULL)
      OR (source_type = 'ADMIN_GRANT' AND payment_id IS NULL));
ALTER TABLE premium_access_periods ADD COLUMN IF NOT EXISTS revoked_at TIMESTAMPTZ;
ALTER TABLE premium_access_periods ADD COLUMN IF NOT EXISTS granted_by BIGINT REFERENCES users(user_id);
ALTER TABLE premium_access_periods ADD COLUMN IF NOT EXISTS revoked_by BIGINT REFERENCES users(user_id);
ALTER TABLE premium_access_periods ADD COLUMN IF NOT EXISTS admin_reason VARCHAR(1000);
ALTER TABLE premium_access_periods DROP CONSTRAINT IF EXISTS ck_premium_manual_grant;
ALTER TABLE premium_access_periods ADD CONSTRAINT ck_premium_manual_grant
  CHECK (source_type <> 'ADMIN_GRANT' OR (granted_by IS NOT NULL AND length(btrim(admin_reason)) > 0));
CREATE INDEX IF NOT EXISTS ix_premium_active_periods ON premium_access_periods(user_id, ends_at DESC)
  WHERE revoked_at IS NULL;

COMMIT;
